---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: Erfahren Sie, wie die Kapazitätsbegriffe für Ihr Speichersystem gelten. 
---
= Erfahren Sie mehr über die Kapazitätsterminologie in SANtricity-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie die Kapazitätsbegriffe für Ihr Speichersystem gelten.



== Speicherobjekte

Die folgende Terminologie beschreibt die verschiedenen Arten von Speicherobjekten, die mit Ihrem Speicherarray interagieren können.

[cols="25h,~"]
|===
| Speicherobjekt | Beschreibung 


 a| 
Host
 a| 
Ein Host ist ein Server, der E/A an ein Volume auf einem Storage-Array sendet.



 a| 
LUN
 a| 
Eine logische Einheitennummer (LUN) ist die Nummer, die dem Adressraum zugewiesen wird, den ein Host für den Zugriff auf ein Volume verwendet. Das Volume wird dem Host als Kapazität in Form einer LUN präsentiert.

Jeder Host verfügt über einen eigenen LUN-Adressraum. Daher kann dieselbe LUN von verschiedenen Hosts verwendet werden, um auf unterschiedliche Volumes zuzugreifen.



 a| 
Mirror Konsistenzgruppe
 a| 
Eine Konsistenzgruppe ist ein Container für ein oder mehrere gespiegelte Paare. Für asynchrone Spiegelungsvorgänge müssen Sie eine Konsistenzgruppe erstellen.



 a| 
Gespiegeltes Volumenpaar
 a| 
Ein gespiegeltes Paar besteht aus zwei Volumina, einem primären Volume und einem sekundären Volume.



 a| 
Pool
 a| 
Ein Pool ist eine Gruppe von Laufwerken, die logisch zusammengefasst sind. Sie können einen Pool verwenden, um ein oder mehrere Volumes zu erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einem Pool oder einer Volume-Gruppe.)



 a| 
Snapshot-Konsistenzgruppe
 a| 
Eine Snapshot-Konsistenzgruppe ist eine Sammlung von Volumes, die beim Erstellen eines Snapshot-Images als eine Einheit behandelt werden. Jedes dieser Volumes hat sein eigenes Snapshot-Image, aber alle Images werden zum selben Zeitpunkt erstellt.



 a| 
Snapshot-Gruppe
 a| 
Eine Snapshot-Gruppe ist eine Sammlung von Snapshot-Images von einem einzelnen Basis-Volume.



 a| 
Snapshot-Volume
 a| 
Ein Snapshot-Volume ermöglicht dem Host den Zugriff auf Daten im Snapshot-Image. Das Snapshot-Volume verfügt über eine eigene reservierte Kapazität, die alle Änderungen am Basis-Volume speichert, ohne das ursprüngliche Snapshot-Image zu beeinträchtigen.



 a| 
Volumen
 a| 
Ein Volume ist ein Container, in dem Anwendungen, Datenbanken und Dateisysteme Daten speichern. Es ist die logische Komponente, die für den Host erstellt wird, um auf den Speicher des Speichersystems zuzugreifen.



 a| 
Volume-Gruppe
 a| 
Eine Volume-Gruppe ist ein Container für Volumes mit gemeinsamen Eigenschaften. Eine Volume-Gruppe hat eine definierte Kapazität und ein definiertes RAID-Level. Sie können eine Volume-Gruppe verwenden, um ein oder mehrere Volumes zu erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einer Volume-Gruppe oder einem Pool.)

|===


== Speicherkapazität

Die folgende Terminologie beschreibt die verschiedenen Kapazitätstypen, die auf Ihrem Storage-Array verwendet werden.

[cols="25h,~"]
|===
| Kapazitätstyp | Beschreibung 


 a| 
Zugewiesene Kapazität
 a| 
Die zugewiesene Kapazität ist die physische Kapazität, die aus den Laufwerken in einem Pool oder einer Volumengruppe zugewiesen wird.

Sie verwenden die zugewiesene Kapazität, um Volumes zu erstellen und für Copy Services-Operationen.



 a| 
Freie Kapazität
 a| 
Freie Kapazität ist die in einem Pool oder einer Volumengruppe verfügbare Kapazität, die noch nicht für Volumenerstellungs- oder Kopierdiensteoperationen und Speicherobjekte zugewiesen wurde.



 a| 
Pool- oder Volumengruppenkapazität
 a| 
Pool-, Volume- oder Volume-Gruppenkapazität ist die Kapazität in einem Speichersystem, die einem Pool oder einer Volume-Gruppe zugewiesen wurde. Diese Kapazität wird verwendet, um Volumes zu erstellen und die verschiedenen Kapazitätsanforderungen von Copy Services-Operationen und Speicherobjekten zu erfüllen.



 a| 
Nicht nutzbare Kapazität des Pools
 a| 
Die nicht nutzbare Poolkapazität ist der Speicherplatz in einem Pool, der aufgrund nicht übereinstimmender Laufwerksgrößen nicht verwendet werden kann.



 a| 
Erhaltungskapazität
 a| 
Die Reservekapazität ist die Menge an Kapazität (Anzahl der Laufwerke), die in einem Pool reserviert ist, um potenzielle Laufwerksausfälle zu unterstützen.



 a| 
Gemeldete Kapazität
 a| 
Die gemeldete Kapazität ist die Kapazität, die dem Host gemeldet wird und auf die der Host zugreifen kann.



 a| 
Reservierte Kapazität
 a| 
Die reservierte Kapazität ist die physisch zugewiesene Kapazität, die für jeden Kopiervorgang und jedes Speicherobjekt verwendet wird. Sie ist für den Host nicht direkt lesbar.



 a| 
SSD-Cache
 a| 
SSD-Cache ist eine Gruppe von Solid-State-Disks (SSD), die Sie in Ihrem Storage-Array logisch zusammenfassen. Die SSD-Cache-Funktion speichert die am häufigsten aufgerufenen Daten ("heiße" Daten) auf SSDs mit geringerer Latenz, um Anwendungs-Workloads dynamisch zu beschleunigen.



 a| 
Nicht zugewiesene Kapazität
 a| 
Nicht zugewiesene Kapazität ist der Speicherplatz in einem Speichersystem, der *nicht* einem Pool oder einer Volumengruppe zugewiesen wurde.



 a| 
Beschriebene Kapazität
 a| 
Die geschriebene Kapazität ist die Kapazitätsmenge, die aus der reservierten Kapazität für Thin Volumes geschrieben wurde.

|===