---
permalink: sm-storage/change-the-settings-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, host 
summary: Sie können den Namen, den Host-Betriebssystemtyp und die zugehörigen Host-Cluster für einen Host ändern. 
---
= Ändern Sie die Einstellungen für einen Host im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Namen, den Host-Betriebssystemtyp und die zugehörigen Host-Cluster für einen Host ändern.

.Schritte
. Menü auswählen:Storage[Hosts].
. Wählen Sie den Host aus, den Sie bearbeiten möchten, und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Es erscheint ein Dialogfeld, das die aktuellen Host-Einstellungen anzeigt.

. Wenn sie noch nicht ausgewählt ist, klicken Sie auf die Registerkarte *Properties*.
. Ändern Sie die Einstellungen nach Bedarf.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Name
 a| 
Sie können den vom Benutzer angegebenen Namen des Hosts ändern. Die Angabe eines Namens für den Host ist erforderlich.



 a| 
Zugehöriger Hostcluster
 a| 
Sie können eine der folgenden Optionen wählen:

** *Keine* -- Der Host bleibt ein eigenständiger Host. Wenn der Host einem Hostcluster zugeordnet war, entfernt das System den Host aus dem Cluster.
** *<Host Cluster>* -- Das System ordnet den Host dem ausgewählten Cluster zu.




 a| 
Host-Betriebssystemtyp
 a| 
Sie können den Typ des Betriebssystems ändern, das auf dem von Ihnen definierten Host ausgeführt wird.

|===
====
. Klicken Sie auf *Speichern*.

