---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: Mit der Funktion „Volume kopieren“ können Sie eine zeitpunktgenaue Kopie eines Volumes erstellen, indem Sie zwei separate Volumes, das Quell-Volume und das Ziel-Volume, auf demselben Storage-Array erstellen. 
---
= Erfahren Sie mehr über Copy Volume im SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit der Funktion „Volume kopieren“ können Sie eine zeitpunktgenaue Kopie eines Volumes erstellen, indem Sie zwei separate Volumes, das Quell-Volume und das Ziel-Volume, auf demselben Storage-Array erstellen.

Diese Funktion führt eine byteweise Kopie vom Quellvolume auf das Ziel-Volume durch, sodass die Daten auf dem Ziel-Volume mit den Daten auf dem Quellvolume identisch sind.



== Datenkopie für besseren Zugriff

Wenn sich Ihre Speicheranforderungen für ein Volume ändern, können Sie die Funktion „Copy Volume“ verwenden, um Daten von Pools oder Volume-Gruppen, die kleinere Kapazitätslaufwerke verwenden, auf Pools oder Volume-Gruppen, die größere Kapazitätslaufwerke verwenden, zu kopieren. Beispielsweise können Sie die Funktion „Copy Volume“ wie folgt verwenden:

* Daten auf größere Laufwerke verschieben.
* Wechseln Sie zu Laufwerken mit höherer Datentransferrate.
* Wechsel zu Laufwerken mit neuen Technologien für höhere Leistung.
* Ändern Sie ein Thin-Volume in ein Thick-Volume.


Quell- und Ziel-Volumes der Kopie müssen die gleiche gemeldete host-adressierbare/logische Blockgröße (Sektorgröße) aufweisen.

Die gemeldeten Volume-Blockgrößen sind:

* *Native Blockgröße* – Die Blockgröße des Volumes entspricht der Blockgröße des Laufwerks, entweder 512 oder 4K.
* *Emulierte 512-Blockgröße* – Laufwerke sind 4K, aber die gemeldete Blockgröße ist 512.




== Ändern Sie ein Thin Volume in ein Thick Volume

Wenn Sie ein dünnes Volume in ein dickes Volume ändern möchten, verwenden Sie die Funktion „Volume kopieren“, um eine Kopie des dünnen Volumes zu erstellen. Das Ziel einer „Volume kopieren“-Operation ist immer ein dickes Volume.

[NOTE]
====
System Manager bietet keine Option zum Erstellen von Thin Volumes. Wenn Sie Thin Volumes erstellen möchten, verwenden Sie die Command Line Interface (CLI).

====


== Sicherungsdaten

Mit der Funktion „Volume kopieren“ können Sie ein Volume sichern, indem Sie Daten von einem Volume auf ein anderes Volume desselben Storage-Arrays kopieren. Sie können das Ziel-Volume als Backup für das Quell-Volume, für Systemtests oder zur Sicherung auf ein anderes Gerät, wie zum Beispiel ein Tape-Laufwerk, verwenden.



== Snapshot-Volume-Daten auf das Basis-Volume wiederherstellen

Wenn Sie Daten vom zugehörigen Snapshot-Volume auf das Basisvolume wiederherstellen müssen, können Sie die Funktion „Volume kopieren“ verwenden, um die Daten vom Snapshot-Volume auf das Basisvolume zu kopieren. Sie können eine Volume-Kopie der Daten auf dem Snapshot-Volume erstellen und dann die Daten auf das Basisvolume kopieren.



== Quell- und Ziel-Volumes

Die folgende Tabelle gibt die Typen von Volumes an, die für Quell- und Ziel-Volumes mit der Funktion „Volume kopieren“ verwendet werden können.

[cols="1a,1a,1a,1a"]
|===
| Volumentyp | Offline-Volume-Kopie-Quellvolume | Online-Volume-Kopie-Quellvolume | Online- und Offline-Volume 


 a| 
Thick Volume in einem Pool
 a| 
Ja
 a| 
Ja
 a| 
Ja



 a| 
Thick Volume in einer Volume-Gruppe
 a| 
Ja
 a| 
Ja
 a| 
Ja



 a| 
Thin Volume
 a| 
Ja^1^
 a| 
Ja
 a| 
Nein



 a| 
Snapshot-Volume
 a| 
Ja^2^
 a| 
Nein
 a| 
Nein



 a| 
Snapshot-Basis-Volume
 a| 
Ja
 a| 
Ja
 a| 
Nein



 a| 
Primär-Volume für Remote Mirror
 a| 
Ja^3^
 a| 
Ja
 a| 
Nein

|===
^1^ Das Ziel-Volume muss eine Kapazität haben, die gleich oder größer als die vom Thin Volume gemeldete Kapazität ist.

^2^ Sie können die Snapshot-Volume-Kopie erst verwenden, nachdem der Online-Kopiervorgang abgeschlossen ist.

^3^ Wenn das Quell-Volume ein Primär-Volume ist, muss die Kapazität des Ziel-Volumes gleich oder größer als die nutzbare Kapazität des Quell-Volumes sein.
