---
permalink: sm-storage/delete-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, consistency, group 
summary: Sie können Snapshot-Konsistenzgruppen, die nicht mehr benötigt werden, löschen. 
---
= Löschen einer Snapshot-Konsistenzgruppe im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Snapshot-Konsistenzgruppen, die nicht mehr benötigt werden, löschen.

.Bevor Sie beginnen
Bestätigen Sie, dass die Images aller Mitgliedsvolumes nicht mehr für Sicherungs- oder Testzwecke benötigt werden.

.Über diese Aufgabe
Dieser Vorgang löscht alle Snapshot-Images oder Zeitpläne, die mit der Snapshot-Konsistenzgruppe verknüpft sind.

.Schritte
. Menü auswählen:Storage[Snapshots].
. Wählen Sie die Registerkarte *Snapshot Consistency Groups* aus.
. Wählen Sie die Snapshot-Konsistenzgruppe aus, die Sie löschen möchten, und wählen Sie dann menu:Uncommon Tasks[Delete].
+
Das Dialogfeld „Snapshot-Konsistenzgruppe löschen bestätigen“ wird angezeigt.

. Bestätigen Sie, dass Sie diesen Vorgang ausführen möchten, und klicken Sie dann auf *Löschen*.


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Löscht alle vorhandenen Snapshot-Images und Snapshot-Volumes aus der Snapshot-Konsistenzgruppe.
* Löscht alle zugehörigen Snapshot-Images, die für jedes Mitgliedsvolume in der Snapshot-Konsistenzgruppe existieren.
* Löscht alle zugehörigen Snapshot-Volumes, die für jedes Mitgliedsvolume in der Snapshot-Konsistenzgruppe existieren.
* Löscht alle zugehörigen reservierten Kapazitäten für jedes Mitgliedsvolume in der Snapshot Konsistenzgruppe (wenn ausgewählt).

