---
permalink: sm-storage/delete-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, group 
summary: Sie löschen eine Snapshot-Gruppe, wenn Sie deren Daten endgültig löschen und sie aus dem System entfernen möchten. Durch das Löschen einer Snapshot-Gruppe wird reservierte Kapazität für die Wiederverwendung im Pool oder in der Volume-Gruppe freigegeben. 
---
= Eine Snapshot-Gruppe im SANtricity System Manager löschen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie löschen eine Snapshot-Gruppe, wenn Sie deren Daten endgültig löschen und sie aus dem System entfernen möchten. Durch das Löschen einer Snapshot-Gruppe wird reservierte Kapazität für die Wiederverwendung im Pool oder in der Volume-Gruppe freigegeben.

.Über diese Aufgabe
Wenn eine Snapshot-Gruppe gelöscht wird, werden auch alle Snapshot Images in der Gruppe gelöscht.

.Schritte
. Menü auswählen:Storage [Pools & Volume Groups].
. Klicken Sie auf die Registerkarte *Reserved Capacity*.
. Wählen Sie die Snapshot-Gruppe aus, die Sie löschen möchten, und klicken Sie dann auf menu:Uncommon Tasks[Delete snapshot group].
+
Das Dialogfeld „Snapshot-Gruppe löschen bestätigen“ wird angezeigt.

. Tippen `delete` zur Bestätigung.


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Löscht alle Snapshot-Images, die mit der Snapshot-Gruppe verknüpft sind.
* Deaktiviert alle Snapshot-Volumes, die mit den Images der Snapshot-Gruppe verknüpft sind.
* Löscht die reservierte Kapazität, die für die Snapshot-Gruppe existiert.

