---
permalink: sm-storage/delete-host-or-host-cluster.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, host, host cluster 
summary: Sie können einen Host oder einen Hostcluster löschen. 
---
= Einen Host oder Hostcluster im SANtricity System Manager löschen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Host oder einen Hostcluster löschen.

.Über diese Aufgabe
Beachten Sie diese Richtlinien, wenn Sie einen Host oder einen Host-Cluster löschen:

* Alle spezifischen Volume-Zuweisungen werden gelöscht, und die zugehörigen Volumes stehen für eine neue Zuweisung zur Verfügung.
* Ist der Host Teil eines Hostclusters mit eigenen spezifischen Zuweisungen, bleibt der Hostcluster unberührt. Ist der Host jedoch Teil eines Hostclusters, das keine weiteren Zuweisungen hat, erben der Hostcluster und alle anderen zugehörigen Hosts oder Host-Port-IDs alle Standardzuweisungen.
* Sämtliche Host-Port-Kennungen, die dem Host zugeordnet waren, werden undefiniert.


.Schritte
. Menü auswählen:Storage[Hosts].
. Wählen Sie den Host oder Host-Cluster aus, den Sie löschen möchten, und klicken Sie dann auf *Löschen*.
+
Das Bestätigungsdialogfeld wird angezeigt.

. Bestätigen Sie, dass Sie die Operation durchführen möchten, und klicken Sie dann auf *Löschen*.


.Ergebnisse
Wenn Sie einen Host gelöscht haben, führt das System die folgenden Aktionen aus:

* Löscht den Host und entfernt ihn, falls zutreffend, aus dem Host-Cluster.
* Entzieht allen zugewiesenen Volumes den Zugriff.
* Setzt die zugehörigen Volumes in einen nicht zugewiesenen Zustand zurück.
* Setzt alle mit dem Host verknüpften Host-Port-Kennungen in den Zustand „nicht verknüpft“ zurück.


Wenn Sie einen Hostcluster gelöscht haben, führt das System die folgenden Aktionen aus:

* Löscht den Hostcluster und die zugehörigen Hosts (falls vorhanden).
* Entzieht allen zugewiesenen Volumes den Zugriff.
* Setzt die zugehörigen Volumes in einen nicht zugewiesenen Zustand zurück.
* Setzt alle mit den Hosts verknüpften Host-Port-Kennungen in einen nicht verknüpften Zustand zurück.

