---
permalink: sm-storage/delete-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, volume 
summary: Normalerweise löscht man Volumes, wenn sie mit den falschen Parametern oder der falschen Kapazität erstellt wurden, nicht mehr den Anforderungen der Speicherkonfiguration entsprechen oder Snapshot-Images sind, die nicht mehr für Backup oder Anwendungstests benötigt werden. 
---
= Löschen Sie ein Volume im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalerweise löscht man Volumes, wenn sie mit den falschen Parametern oder der falschen Kapazität erstellt wurden, nicht mehr den Anforderungen der Speicherkonfiguration entsprechen oder Snapshot-Images sind, die nicht mehr für Backup oder Anwendungstests benötigt werden.

Durch das Löschen eines Volumes wird die freie Kapazität im Pool oder in der Volume-Gruppe erhöht. Sie können ein oder mehrere Volumes zum Löschen auswählen.

.Bevor Sie beginnen
Stellen Sie bei den Volumes, die Sie löschen möchten, Folgendes sicher:

* Alle Daten sind gesichert.
* Sämtliche Ein-/Ausgaben (E/A) sind gestoppt.
* Sämtliche Geräte und Dateisysteme sind ausgehängt.


.Über diese Aufgabe
Sie können ein Volume, das eine der folgenden Bedingungen aufweist, nicht löschen:

* Das Volume wird initialisiert.
* Das Volume wird rekonstruiert.
* Das Volume ist Teil einer Volume-Gruppe, die ein Laufwerk enthält, das sich in einer Copyback-Operation befindet.
* Das Volume wird gerade einer Modifikationsoperation unterzogen, wie zum Beispiel einer Änderung der Segmentgröße, es sei denn, das Volume befindet sich jetzt im Status „Fehlgeschlagen“.
* Das Volume hält jede Art von persistenter Reservierung.
* Das Volume ist ein Quell-Volume oder ein Ziel-Volume in einem Kopiervolume mit dem Status Pending, In Progress oder Failed.


[CAUTION]
====
Das Löschen eines Volumes führt zum Verlust aller Daten auf diesen Volumes.

====
[NOTE]
====
Wenn ein Volume eine bestimmte Größe (derzeit 128 TB) überschreitet, wird die Löschung im Hintergrund durchgeführt und der freigegebene Speicherplatz steht möglicherweise nicht sofort zur Verfügung.

====
.Schritte
. Menü auswählen: Storage[Volumes].
. Klicken Sie auf *Delete*.
+
Das Dialogfeld „Volumes löschen“ wird angezeigt.

. Wählen Sie ein oder mehrere Volumes aus, die Sie löschen möchten, und bestätigen Sie, dass Sie den Vorgang ausführen möchten.
. Klicken Sie auf *Delete*.


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Löscht alle zugehörigen Snapshot-Images, Zeitpläne und Snapshot-Volumes.
* Entfernt alle Spiegelungsbeziehungen.
* Erhöht die freie Kapazität im Pool oder in der Volume-Gruppe.

