---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: Reservierte Kapazität wird automatisch erstellt, wenn Kopierdienstvorgänge wie Snapshots oder asynchrone Spiegelungsvorgänge für Ihre Volumes bereitgestellt werden. 
---
= Wie die reservierte Kapazität in der SANtricity-Software funktioniert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reservierte Kapazität wird automatisch erstellt, wenn Kopierdienstvorgänge wie Snapshots oder asynchrone Spiegelungsvorgänge für Ihre Volumes bereitgestellt werden.

Der Zweck der reservierten Kapazität besteht darin, Datenänderungen auf diesen Volumes zu speichern, falls etwas schiefgeht. Wie Volumes wird auch reservierte Kapazität aus Pools oder Volume-Gruppen erstellt.



== Kopierdienstobjekte, die reservierte Kapazität verwenden

Die reservierte Kapazität ist der zugrunde liegende Storage-Mechanismus, der von diesen Copy-Service-Objekten verwendet wird:

* Momentaufnahmengruppen
* Lesen/Schreiben von Snapshot-Volumes
* Konsistenzgruppen-Mitgliedervolumen
* Mirrored-Pair-Volumes


Beim Erstellen oder Erweitern dieser Kopierdienstobjekte müssen Sie neue reservierte Kapazität aus einem Pool oder einer Volumengruppe erstellen. Reservierte Kapazität beträgt typischerweise 40 Prozent des Basisvolumens für Snapshot-Vorgänge und 20 Prozent des Basisvolumens für asynchrone Spiegelungsvorgänge. Reservierte Kapazität variiert jedoch je nach Anzahl der Änderungen an den Originaldaten.



== Thin Volumes und reservierte Kapazität

Bei einem Thin Volume kann die Kapazität nicht erhöht werden, sobald die maximal gemeldete Kapazität von 256 TiB erreicht ist. Stellen Sie sicher, dass die reservierte Kapazität des Thin Volumes auf eine Größe eingestellt ist, die größer als die maximal gemeldete Kapazität ist. (Ein Thin Volume ist immer thin-provisioned, was bedeutet, dass die Kapazität zugewiesen wird, während die Daten auf das Volume geschrieben werden.)

Wenn Sie reservierte Kapazität mithilfe eines Thin Volumes in einem Pool erstellen, beachten Sie die folgenden Aktionen und Ergebnisse für die reservierte Kapazität:

* Wenn die reservierte Kapazität eines Thin Volumes ausfällt, wechselt das Thin Volume selbst nicht automatisch in den Status „Fehlgeschlagen“. Da jedoch alle I/O-Operationen auf einem Thin Volume Zugriff auf das Volume mit reservierter Kapazität benötigen, wird bei jeder I/O-Operation eine Check Condition an den anfragenden Host zurückgegeben. Kann das zugrunde liegende Problem mit dem Volume mit reservierter Kapazität behoben werden, wird dieses wieder in den Optimal-Zustand versetzt und das Thin Volume ist wieder funktionsfähig.
* Wenn Sie ein vorhandenes Thin Volume verwenden, um ein asynchrones Spiegelpaar zu vervollständigen, wird dieses Thin Volume mit einem neuen Volume mit reservierter Kapazität neu initialisiert. Nur die auf der primären Seite bereitgestellten Blöcke werden während des anfänglichen Synchronisierungsprozesses übertragen.




== Kapazitätswarnungen

Das Copy Service-Objekt verfügt über einen konfigurierbaren Kapazitätswarn- und Alarmschwellenwert sowie eine konfigurierbare Reaktion, wenn die reservierte Kapazität voll ist.

Wenn die reservierte Kapazität eines Copy Service-Objekt-Volumes den Füllpunkt erreicht, wird eine Warnung an den Benutzer ausgegeben. Standardmäßig wird diese Warnung ausgegeben, wenn das Volume mit reservierter Kapazität zu 75 Prozent gefüllt ist; Sie können diesen Warnpunkt jedoch nach Bedarf nach oben oder unten anpassen. Wenn Sie diese Warnung erhalten, können Sie die Kapazität des Volumes mit reservierter Kapazität zu diesem Zeitpunkt erhöhen. Jedes Copy Service-Objekt kann diesbezüglich unabhängig konfiguriert werden.



== Verwaiste reservierte Kapazitätsvolumina

Ein verwaistes reserviertes Kapazitätsvolume ist ein Volume, das keine Daten mehr für Copy-Service-Operationen speichert, da das zugehörige Copy-Service-Objekt gelöscht wurde. Als das Copy-Service-Objekt gelöscht wurde, hätte auch das zugehörige reservierte Kapazitätsvolume gelöscht werden sollen. Das reservierte Kapazitätsvolume konnte jedoch nicht gelöscht werden.

Da verwaiste reservierte Kapazitätsvolumes von keinem Host genutzt werden, sind sie Kandidaten für die Rückgewinnung. Löschen Sie das verwaiste reservierte Kapazitätsvolume manuell, damit Sie dessen Kapazität für andere Vorgänge verwenden können.

System Manager benachrichtigt Sie über verwaiste reservierte Kapazitätsvolumes mit der Meldung „Nicht verwendete Kapazität freigeben“ im Benachrichtigungsbereich der Startseite. Sie können auf *Nicht verwendete Kapazität freigeben* klicken, um das Dialogfeld „Nicht verwendete Kapazität freigeben“ anzuzeigen, in dem Sie das verwaiste reservierte Kapazitätsvolume löschen können.



== Merkmale der reservierten Kapazität

* Die für reservierte Kapazität zugewiesene Kapazität muss bei der Volume-Erstellung berücksichtigt werden, um ausreichend freie Kapazität zu behalten.
* Die reservierte Kapazität kann kleiner als das Basisvolume sein (die Mindestgröße beträgt 8 MiB).
* Ein Teil des Speicherplatzes wird von Metadaten belegt, aber er ist sehr gering (192 KiB), sodass er bei der Bestimmung der Größe des reservierten Kapazitäts-Volumes nicht berücksichtigt werden muss.
* Reservierte Kapazität ist von einem Host aus nicht direkt lesbar oder schreibbar.
* Reservierte Kapazität existiert für jedes lesen/schreiben Snapshot-Volume, jede Snapshot-Gruppe, jedes Konsistenzgruppe-Mitglieds-Volume und jedes gespiegelte Paar-Volume.

