---
permalink: sm-storage/manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, manual, host, 
summary: Das Erstellen eines Hosts ist einer der erforderlichen Schritte, damit das Speichersystem weiß, welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen. Sie können einen Host nur manuell erstellen. 
---
= Erfahren Sie mehr über die manuelle Host-Erstellung im SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Erstellen eines Hosts ist einer der erforderlichen Schritte, damit das Speichersystem weiß, welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen. Sie können einen Host nur manuell erstellen.



== Manuelle Erstellung

Die manuelle Host-Erstellung ermöglicht es Ihnen, sicherzustellen, dass die von den Speicherarray-Controllern erkannten Host-Port-Kennungen korrekt den Hosts zugeordnet werden.

Während der manuellen Host-Erstellung ordnen Sie Host-Port-IDs zu, indem Sie diese aus einer Liste auswählen oder manuell eingeben. Nachdem Sie einen Host erstellt haben, können Sie ihm Volumes zuweisen oder ihn einem Host-Cluster hinzufügen, wenn Sie den Zugriff auf Volumes gemeinsam nutzen möchten.
