---
permalink: sm-storage/remove-member-volumes-from-a-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, member volume, snapshot, consistency group 
summary: Sie können ein Mitgliedsvolume aus einer bestehenden Snapshot-Konsistenzgruppe entfernen. 
---
= Entfernen eines Mitgliedsvolumes aus einer Snapshot-Konsistenzgruppe im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Mitgliedsvolume aus einer bestehenden Snapshot-Konsistenzgruppe entfernen.

.Über diese Aufgabe
Wenn Sie ein Mitgliedsvolume aus einer Snapshot-Konsistenzgruppe entfernen, löscht System Manager automatisch die mit diesem Mitgliedsvolume verknüpften Snapshot-Objekte.

.Schritte
. Menü auswählen:Storage[Snapshots].
. Klicken Sie auf die Registerkarte *Snapshot Consistency Groups*.
. Erweitern Sie die Snapshot-Konsistenzgruppe, die Sie ändern möchten, indem Sie das Pluszeichen (+) daneben auswählen.
. Wählen Sie das Mitgliedsvolume aus, das Sie entfernen möchten, und klicken Sie dann auf *Remove*.
. Bestätigen Sie, dass Sie den Vorgang durchführen möchten, und klicken Sie dann auf *Remove*.


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Löscht alle Snapshot-Images und Snapshot-Volumes, die mit dem Member-Volume verknüpft sind.
* Löscht die mit dem Mitgliedsvolume verknüpfte Snapshot-Gruppe.
* Das Mitgliedsvolumen wird ansonsten weder verändert noch gelöscht.

