---
permalink: sm-storage/requirements-and-guidelines-for-snapshots.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, guidelines, snapshots 
summary: Beachten Sie beim Erstellen und Verwenden von Snapshots die folgenden Anforderungen und Richtlinien. 
---
= Anforderungen und Richtlinien für Snapshots im SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beachten Sie beim Erstellen und Verwenden von Snapshots die folgenden Anforderungen und Richtlinien.



== Snapshot Images und Snapshot-Gruppen

* Jedes Snapshot-Image ist genau einer Snapshot-Gruppe zugeordnet.
* Eine Snapshot-Gruppe wird beim ersten Erstellen eines geplanten oder sofortigen Snapshot-Images für ein zugehöriges Objekt erstellt. Dadurch wird reservierte Kapazität erstellt.
+
Sie können Snapshot-Gruppen auf der Seite „Pools & Volume Groups“ anzeigen.

* Geplante Snapshot-Images werden nicht erstellt, wenn das Storage-Array offline oder ausgeschaltet ist.
* Wenn Sie eine Snapshot-Gruppe löschen, die einen Snapshot-Zeitplan hat, wird auch der Snapshot-Zeitplan gelöscht.
* Wenn Sie ein Snapshot-Volume besitzen, das Sie nicht mehr benötigen, können Sie es zusammen mit der zugehörigen reservierten Kapazität wiederverwenden, anstatt es zu löschen. Dadurch wird ein anderes Snapshot-Volume desselben Basis-Volumes erstellt. Sie können das Snapshot-Volume oder das Snapshot-Konsistenzgruppen-Snapshot-Volume demselben Snapshot-Image oder einem anderen Snapshot-Image zuordnen, solange sich das Snapshot-Image im selben Basis-Volume befindet.




== Snapshot-Konsistenzgruppe

* Eine Snapshot-Konsistenzgruppe enthält eine Snapshot-Gruppe für jedes Volume, das Mitglied der Snapshot-Konsistenzgruppe ist.
* Sie können eine Snapshot-Konsistenzgruppe nur einem Zeitplan zuordnen.
* Wenn Sie eine Snapshot-Konsistenzgruppe löschen, die einen Snapshot-Zeitplan hat, wird auch der Snapshot-Zeitplan gelöscht.
* Sie können eine Snapshot-Gruppe, die mit einer Snapshot-Konsistenzgruppe verknüpft ist, nicht einzeln verwalten. Stattdessen müssen Sie die Verwaltungsvorgänge (Snapshot-Image erstellen, Snapshot-Image oder Snapshot-Gruppe löschen und Snapshot-Image zurücksetzen) auf Ebene der Snapshot-Konsistenzgruppe durchführen.




== Grundvolumen

* Ein Snapshot-Volume muss die gleichen Data Assurance (DA)- und Sicherheitseinstellungen wie das zugehörige Base-Volume aufweisen.
* Sie können kein Snapshot-Volume eines ausgefallenen Basis-Volumes erstellen.
* Befindet sich das Basisvolume in einer Volume-Gruppe, können sich die Mitgliedsvolumes einer zugehörigen Snapshot-Konsistenzgruppe entweder in einem Pool oder in einer Volume-Gruppe befinden.
* Wenn sich ein Basisvolume auf einem Pool befindet, müssen sich alle Mitgliedsvolumes einer zugehörigen Snapshot-Konsistenzgruppe auf demselben Pool wie das Basisvolume befinden.




== Reservierte Kapazität

* Die reservierte Kapazität ist nur einem Basis-Volume zugeordnet.
* Die Verwendung eines Zeitplans kann zu einer großen Anzahl von Snapshot Images führen. Stellen Sie sicher, dass Sie über ausreichend reservierte Kapazität für geplante Snapshots verfügen.
* Das reservierte Kapazitätsvolume für eine Snapshot-Konsistenzgruppe muss die gleichen Data Assurance (DA)- und Sicherheitseinstellungen aufweisen wie das zugehörige Basisvolume für das Snapshot-Konsistenzgruppen-Mitgliedsvolume.




== Ausstehende Snapshot-Images

Die Erstellung eines Snapshot-Images kann unter folgenden Bedingungen im Status „Pending“ verbleiben:

* Das Basisvolume, das dieses Snapshot-Image enthält, ist Mitglied einer asynchronen Spiegelgruppe.
* Das Basisvolume befindet sich derzeit in einem Synchronisierungsvorgang. Die Erstellung des Snapshot-Images wird abgeschlossen, sobald der Synchronisierungsvorgang beendet ist.




== Maximale Anzahl von Snapshot-Bildern

* Wenn ein Volume Mitglied einer Snapshot-Konsistenzgruppe ist, erstellt System Manager eine Snapshot-Gruppe für dieses Mitgliedsvolume. Diese Snapshot-Gruppe wird auf die maximal zulässige Anzahl von Snapshot-Gruppen pro Basisvolume angerechnet.
* Wenn Sie versuchen, ein Snapshot-Image für eine Snapshot-Gruppe oder eine Snapshot-Konsistenzgruppe zu erstellen, die zugehörige Gruppe aber bereits die maximale Anzahl an Snapshot-Images erreicht hat, haben Sie zwei Möglichkeiten:
+
** Aktivieren Sie die automatische Löschung für die Snapshot-Gruppe oder die Snapshot-Konsistenzgruppe.
** Löschen Sie manuell ein oder mehrere Snapshot-Images aus der Snapshot-Gruppe oder der Snapshot-Konsistenzgruppe und wiederholen Sie den Vorgang.






== Automatische Löschung

Wenn die Snapshot-Gruppe oder die Snapshot-Konsistenzgruppe für die automatische Löschung aktiviert ist, löscht der System Manager das älteste Snapshot-Image, wenn das System ein neues für die Gruppe erstellt.



== Rollback-Operation

* Sie können die folgenden Aktionen nicht ausführen, während ein Rollback-Vorgang läuft:
+
** Löschen Sie das Snapshot-Image, das für das Rollback verwendet wird.
** Erstellen Sie ein neues Snapshot-Image für ein Basis-Volume, das an einer Rollback-Operation teilnimmt.
** Ändern Sie die Repository-Full-Policy der zugehörigen Snapshot-Gruppe.


* Ein Rollback-Vorgang kann nicht gestartet werden, wenn einer dieser Vorgänge ausgeführt wird:
+
** Kapazitätserweiterung (Hinzufügen von Kapazität zu einem Pool oder einer Volume-Gruppe)
** Volumenerweiterung (Erhöhung der Kapazität eines Volumes)
** RAID-Level-Änderung für eine Volume-Gruppe
** Segmentgrößenänderung für ein Volume


* Sie können keinen Rollback-Vorgang starten, wenn das Basisvolume an einer Volume-Kopie beteiligt ist.
* Sie können keinen Rollback-Vorgang starten, wenn das Basisvolume ein sekundäres Volume in einem Remote-Mirror ist.
* Ein Rollback-Vorgang schlägt fehl, wenn ein Teil der verwendeten Kapazität im zugehörigen Snapshot-Repository-Volume über unlesbare Sektoren verfügt.

