---
permalink: sm-mirroring/change-mirror-consistency-group-role-to-primary-or-secondary.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mirror, consistency group, primary, secondary 
summary: Sie können die Rolle zwischen Spiegel-Konsistenzgruppen aus administrativen Gründen oder im Falle einer Katastrophe auf dem lokalen Speichersystem ändern. 
---
= Ändern Sie die Rolle der Spiegel-Konsistenzgruppe auf primär oder sekundär im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Rolle zwischen Spiegel-Konsistenzgruppen aus administrativen Gründen oder im Falle einer Katastrophe auf dem lokalen Speichersystem ändern.

.Über diese Aufgabe
Auf dem lokalen Speichersystem erstellte Spiegel-Konsistenzgruppen haben die primäre Rolle. Auf dem Remote-Speichersystem erstellte Spiegel-Konsistenzgruppen haben die sekundäre Rolle. Sie können entweder die lokale Spiegel-Konsistenzgruppe zu einer sekundären Rolle herabstufen oder die Remote-Spiegel-Konsistenzgruppe zu einer primären Rolle hochstufen.

.Schritte
. Menü auswählen:Storage[Asynchronous Mirroring].
. Wählen Sie die Registerkarte *Mirror Consistency Groups* aus.
+
Die Tabelle „Mirror Consistency Group“ wird angezeigt und zeigt alle mit dem Speicherarray verknüpften Mirror Consistency Groups an.

. Wählen Sie die Spiegel-Konsistenzgruppe aus, deren Rolle Sie ändern möchten, und wählen Sie dann Menü:Mehr[Rolle ändern in <Primary | Secondary>]*>*.
+
Das System zeigt eine Bestätigung an.

. Bestätigen Sie, dass Sie die Rolle der Spiegel-Konsistenzgruppe ändern möchten, und klicken Sie dann auf *Rolle ändern*.
+
[NOTE]
====
Das System zeigt das Dialogfeld „Cannot Contact Storage Array“ an, wenn eine Rollenänderung angefordert wird, das Remote-Speicherarray aber nicht erreichbar ist. Klicken Sie auf *Yes*, um die Rollenänderung zu erzwingen.

====


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Die Tabelle „Mirror Consistency Group“ zeigt den Status „pending“ oder „in-progress“ neben der Mirror Consistency Group an, deren Rolle geändert wird. Sie können einen Role Change-Vorgang, der pending ist, abbrechen, indem Sie auf den Link *Cancel* in der Tabellenzelle klicken.
* Wenn die zugehörige Spiegel-Konsistenzgruppe kontaktiert werden kann, ändern sich die Rollen zwischen den Spiegel-Konsistenzgruppen. System Manager stuft die sekundäre Spiegel-Konsistenzgruppe zur primären Rolle hoch oder die primäre Spiegel-Konsistenzgruppe zur sekundären Rolle herab (abhängig von Ihrer Auswahl). Die Rollenänderung betrifft alle gespiegelten Paare innerhalb der ausgewählten Spiegel-Konsistenzgruppe.

