---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: Wenn Sie ein primäres Volume auf einem älteren Speichersystem erstellt haben, das nicht von SANtricity System Manager verwaltet werden kann, können Sie das sekundäre Volume auf diesem System mit System Manager erstellen. 
---
= Schließen Sie ein Spiegelpaar für primäre Volumes ab, die auf einem Legacy-System im SANtricity System Manager erstellt wurden.
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein primäres Volume auf einem älteren Storage Array erstellt haben, das nicht von SANtricity System Manager verwaltet werden kann, können Sie das sekundäre Volume auf diesem Array mit SANtricity System Manager erstellen.

.Über diese Aufgabe
Sie können asynchrone Spiegelung zwischen älteren Arrays, die eine andere Schnittstelle verwenden, und neueren Arrays durchführen, die vom System Manager verwaltet werden können.

* Wenn Sie eine Spiegelung zwischen zwei Speicherarrays durchführen, die System Manager verwenden, können Sie diese Aufgabe überspringen, da Sie das gespiegelte Paar bereits in der Sequenz zur Erstellung des gespiegelten Paars abgeschlossen haben.
* Führen Sie diese Aufgabe auf dem entfernten Storage-Array aus.


.Schritte
. Menü auswählen:Storage[Asynchronous Mirroring].
. Wählen Sie die Registerkarte *Mirrored Pair* aus.
+
Die Tabelle „Gespiegelte Paare“ wird angezeigt und zeigt alle gespiegelten Paare an, die mit dem Storage Array verknüpft sind.

. Suchen Sie das Spiegelpaar-Volume mit dem Status „Unvollständig“ und klicken Sie dann auf den Link *Spiegelpaar vervollständigen*, der in der Spalte Spiegelpaar angezeigt wird.
. Wählen Sie, ob Sie die Sequenz zur Erstellung des gespiegelten Paares automatisch oder manuell abschließen möchten, indem Sie eines der folgenden Optionsfelder auswählen:
+
** *Automatisch* -- Neues sekundäres Volume erstellen.
+
Übernehmen Sie die Standardeinstellungen für die Remote-Seite des gespiegelten Paares, indem Sie einen vorhandenen Pool oder eine Volumengruppe auswählen, in der Sie das sekundäre Volume erstellen möchten. Verwenden Sie diese empfohlene Option, um die reservierte Kapazität für das sekundäre Volume mit den Standardeinstellungen zuzuweisen.

** *Manuell* -- Wählen Sie ein vorhandenes Volume aus.
+
Definieren Sie Ihre eigenen Parameter für das sekundäre Volume.

+
... Klicken Sie auf *Weiter*, um das sekundäre Volume auszuwählen.
... Wählen Sie ein vorhandenes Volume aus, das Sie als sekundäres Volume verwenden möchten, und klicken Sie dann auf *Weiter*, um die reservierte Kapazität zuzuweisen.
... Weisen Sie die reservierte Kapazität zu. Führen Sie einen der folgenden Schritte aus:
+
**** Akzeptieren Sie die Standardeinstellungen.
+
Die Standardeinstellung für die reservierte Kapazität beträgt 20% der Kapazität des Basisvolumens, und diese Kapazität ist in der Regel ausreichend.

**** Weisen Sie Ihre eigenen reservierten Kapazitätseinstellungen zu, um Ihren Datenspeicherbedarf im Zusammenhang mit asynchronem Spiegeln zu decken.
+
Der benötigte Speicherplatz variiert, abhängig von der Häufigkeit und Größe der E/A-Schreibvorgänge auf das primäre Volume und davon, wie lange Sie die Kapazität vorhalten müssen. Wählen Sie im Allgemeinen eine größere Kapazität für die reservierte Kapazität, wenn eine oder beide der folgenden Bedingungen zutreffen:

+
***** Sie beabsichtigen, das gespiegelte Paar über einen längeren Zeitraum zu behalten.
***** Aufgrund hoher I/O-Aktivität ändert sich ein großer Prozentsatz der Datenblöcke auf dem primären Volume. Verwenden Sie historische Leistungsdaten oder andere Betriebssystem-Utilities, um die typische I/O-Aktivität auf dem primären Volume zu ermitteln.








. Wählen Sie *Complete*.


.Ergebnisse
System Manager führt die folgenden Aktionen aus:

* Erstellt das sekundäre Volume auf dem entfernten Speichersystem und weist reservierte Kapazität für die entfernte Seite des gespiegelten Paares zu.
* Beginnt die initiale Synchronisierung zwischen dem lokalen Speicherarray und dem Remote-Speicherarray.
* Wenn das gespiegelte Volume ein Thin Volume ist, werden während der ersten Synchronisierung nur die zugewiesenen Blöcke auf das sekundäre Volume übertragen. Dieser Transfer reduziert die Datenmenge, die für den Abschluss der ersten Synchronisierung übertragen werden muss.
* Erstellt die reservierte Kapazität für das gespiegelte Paar auf dem lokalen Storage-Array und auf dem entfernten Storage-Array.

