---
permalink: sm-mirroring/deactivate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, deactivate, synchronous, mirroring, adapter, host, bus, 
summary: 'Sie können die Funktion „Synchronous Mirroring“ auf einem Speichersystem deaktivieren, um die normale Nutzung des Host-Bus-Adapters (HBA)-Host-Port 4 wiederherzustellen, der für die Übertragung von gespiegelten Daten reserviert war.' 
---
= Deaktivieren Sie die synchrone Spiegelung im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Funktion „Synchronous Mirroring“ auf einem Speichersystem deaktivieren, um die normale Nutzung des Host-Bus-Adapters (HBA)-Host-Port 4 wiederherzustellen, der für die Übertragung von gespiegelten Daten reserviert war.

.Bevor Sie beginnen
Sie müssen alle synchronen Spiegelungsbeziehungen gelöscht haben. Überprüfen Sie, ob alle gespiegelten Paare aus dem Storage-Array gelöscht wurden.

.Schritte
. Menü auswählen: Storage [Synchronous Mirroring].
. Menü auswählen: Uncommon Tasks [Deactivate].
+
Das System zeigt eine Bestätigung an.

. Wählen Sie *Ja* zur Bestätigung aus.


.Ergebnisse
* Der HBA-Hostport 4 des Controllers, der für die synchrone Spiegelungskommunikation vorgesehen war, kann nun Host-Lese- und Schreibanforderungen entgegennehmen.
* Die reservierten Kapazitätsvolumes auf dem Storage-Array werden gelöscht.

