---
permalink: sm-mirroring/synchronous-mirroring-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronous, mirroring, terms 
summary: Erfahren Sie, wie die Begriffe der synchronen Spiegelung auf Ihr Speichersystem zutreffen. 
---
= Erfahren Sie mehr über die Terminologie der synchronen Spiegelung in SANtricity Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie die Begriffe der synchronen Spiegelung auf Ihr Speichersystem zutreffen.

[cols="25h,~"]
|===
| Begriff | Beschreibung 


 a| 
Lokales Speicherarray
 a| 
Das lokale Speicherarray ist das Speicherarray, auf das Sie zugreifen.

Wenn Sie *Primär* in der Spalte „Lokale Rolle“ sehen, bedeutet dies, dass das Speichersystem das Volume enthält, das die primäre Rolle in der Spiegelungsbeziehung einnimmt. Wenn Sie *Sekundär* in der Spalte „Lokale Rolle“ sehen, bedeutet dies, dass das Speichersystem das Volume enthält, das die sekundäre Rolle in der Spiegelungsbeziehung einnimmt.



 a| 
Spiegeltes Paar
 a| 
Ein gespiegeltes Paar besteht aus zwei Volumina, einem primären Volume und einem sekundären Volume.



 a| 
Primärvolume
 a| 
Das primäre Volume eines gespiegelten Paares ist das Quellvolume, das gespiegelt werden soll.



 a| 
Recovery Point Objective (RPO)
 a| 
Recovery Point Objective (RPO) stellt ein Ziel dar, das die als akzeptabel angesehene Differenz zwischen dem primären Volume und dem sekundären Volume in einem gespiegelten Paar angibt. Ein RPO von null bedeutet, dass keine Differenz zwischen dem primären Volume und dem sekundären Volume toleriert werden kann. Ein RPO größer als null bedeutet, dass das sekundäre Volume weniger aktuell ist oder hinter dem primären Volume zurückbleibt.



 a| 
Remote-Speicherarray
 a| 
Das entfernte Speichersystem wird üblicherweise als sekundärer Standort bezeichnet, der in der Regel eine Replik der Daten in einer Spiegelkonfiguration enthält.



 a| 
Reservierte Kapazität
 a| 
Die reservierte Kapazität ist die physisch zugewiesene Kapazität, die für jeden Kopiervorgang und jedes Speicherobjekt verwendet wird. Sie ist für den Host nicht direkt lesbar.



 a| 
Rollenwechsel
 a| 
Rollenwechsel bedeutet, dass die primäre Rolle dem sekundären Volume und umgekehrt zugewiesen wird.



 a| 
sekundäres Volume
 a| 
Das sekundäre Volume eines gespiegelten Paares befindet sich üblicherweise an einem sekundären Standort und enthält eine Replik der Daten.



 a| 
Synchronisierung
 a| 
Die Synchronisierung erfolgt bei der ersten Synchronisierung zwischen dem lokalen Storage-Array und dem entfernten Storage-Array. Die Synchronisierung erfolgt auch, wenn die primären und sekundären Volumes nach einer Kommunikationsunterbrechung nicht mehr synchron sind. Wenn die Kommunikationsverbindung wieder funktioniert, werden alle nicht replizierten Daten mit dem Storage-Array des sekundären Volumes synchronisiert.

|===