---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Sie müssen das Storage-Array mit einem Administratorpasswort konfigurieren, um es vor unberechtigtem Zugriff zu schützen. 
---
= Passwortschutz im SANtricity System Manager verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das Storage-Array mit Passwörtern konfigurieren, um es vor unberechtigtem Zugriff zu schützen.



== Passwörter festlegen und ändern

Beim ersten Start des System Manager werden Sie aufgefordert, ein Administratorkennwort festzulegen. Jeder Benutzer, der das Admin-Kennwort hat, kann Konfigurationsänderungen am Storage-Array vornehmen, wie zum Beispiel das Hinzufügen, Ändern oder Entfernen von Objekten oder Einstellungen. Um das Admin-Kennwort während des ersten Starts festzulegen, siehe link:../san-getstarted/access-sam.html["System Manager aufrufen"].

Aus Sicherheitsgründen können Sie nur fünfmal versuchen, ein Passwort einzugeben, bevor das Speichersystem in einen „Lockout“-Zustand versetzt wird. In diesem Zustand lehnt das Speichersystem weitere Passwortversuche ab. Sie müssen 10 Minuten warten, bis das Speichersystem wieder in den „Normal“-Zustand zurückkehrt, bevor Sie erneut versuchen, ein Passwort einzugeben.

Zusätzlich zum Administratorpasswort enthält das Speichersystem vordefinierte Benutzerprofile mit einer oder mehreren zugeordneten Rollen. Weitere Informationen finden Sie unter link:../sm-settings/permissions-for-mapped-roles.html["Berechtigungen für zugeordnete Rollen"]. Die Benutzerprofile und Zuordnungen können nicht geändert werden. Nur Passwörter können geändert werden. Wenn Sie das Administratorpasswort oder andere Benutzerpasswörter ändern möchten, siehe link:../sm-settings/change-passwords.html["Passwörter ändern"].



== Passwörter nach Zeitüberschreitung der Sitzung erneut eingeben

Das System fordert Sie während einer Verwaltungssitzung nur einmal zur Passworteingabe auf. Eine Sitzung wird jedoch nach 30 Minuten Inaktivität beendet, und Sie müssen das Passwort erneut eingeben. Wenn ein anderer Benutzer, der dasselbe Storage-Array von einem anderen Verwaltungsclient aus verwaltet, das Passwort während Ihrer Sitzung ändert, werden Sie bei dem nächsten Versuch einer Konfigurations- oder Ansichtsoperation zur Passworteingabe aufgefordert.

Sie können die Sitzungs-Zeitüberschreitung anpassen oder die Sitzungs-Zeitüberschreitungen vollständig deaktivieren. Siehe link:../sm-settings/manage-session-timeouts-sam.html["Sitzungs-Zeitüberschreitungen verwalten"].



== Laufwerke oder Passwortschutz entfernen

Wenn Sie passwortgeschützte Laufwerke entfernen oder den Passwortschutz deaktivieren möchten, beachten Sie Folgendes:

* *Wenn Sie Laufwerke mit Passwortschutz entfernen* -- Das Passwort wird in einem reservierten Bereich jedes Laufwerks im Storage-Array gespeichert. Wenn Sie alle Laufwerke aus einem Storage-Array entfernen, funktioniert das Passwort nicht mehr. Um diesen Zustand zu korrigieren, installieren Sie eines der ursprünglichen Laufwerke wieder im Storage-Array.
* *Wenn Sie den Passwortschutz entfernen möchten* -- Wenn Sie nicht mehr möchten, dass Befehle passwortgeschützt sind, geben Sie das aktuelle Administratorpasswort ein und lassen Sie die Textfelder für das neue Passwort leer.


[CAUTION]
====
Die Ausführung von Konfigurationsbefehlen auf einem Speichersystem kann schwerwiegende Schäden verursachen, einschließlich Datenverlust. Aus diesem Grund sollten Sie immer ein Administratorpasswort für Ihr Speichersystem festlegen. Verwenden Sie ein langes Administratorpasswort mit mindestens 15 alphanumerischen Zeichen, um die Sicherheit zu erhöhen.

====