---
permalink: sm-hardware/change-shelf-ids.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, shelf, ids, 
summary: Die Regal-ID ist eine Nummer, die ein Regal im Storage-Array eindeutig identifiziert. Regale sind fortlaufend nummeriert, beginnend mit entweder 00 oder 01, oben links in jeder Regalansicht. 
---
= Ändern Sie Shelf-IDs im SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Regal-ID ist eine Nummer, die ein Regal im Storage-Array eindeutig identifiziert. Regale sind fortlaufend nummeriert, beginnend mit entweder 00 oder 01, oben links in jeder Regalansicht.

.Über diese Aufgabe
Die Controller-Firmware weist die Shelf-ID automatisch zu, aber Sie können diese Nummer ändern, wenn Sie ein anderes Sortierschema erstellen möchten.

.Schritte
. Wählen Sie *Hardware* aus.
. Wählen Sie die Dropdown-Liste für das Controller-Shelf oder das Laufwerks-Shelf aus und wählen Sie dann *ID ändern*.
. Im Dialogfeld „Change Shelf ID“ wählen Sie die Dropdown-Liste aus, um die verfügbaren Nummern anzuzeigen.
+
In diesem Dialogfeld werden die derzeit zugewiesenen IDs für aktive Shelves nicht angezeigt.

. Wählen Sie eine verfügbare Nummer aus, und klicken Sie dann auf *Speichern*.
+
Je nach gewählter Nummer kann die Regalreihenfolge auf der Seite „Hardware“ neu angeordnet werden. Wenn gewünscht, können Sie die Auf-/Ab-Pfeile oben rechts an jedem Regal verwenden, um die Reihenfolge erneut anzupassen.


