---
permalink: sm-hardware/place-controller-in-service-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, place, controller, service, mode, 
summary: Wenn Sie dazu aufgefordert werden, können Sie einen Controller in den Servicemodus versetzen. 
---
= Versetzen Sie einen Controller im SANtricity System Manager in den Servicemodus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie dazu aufgefordert werden, können Sie einen Controller in den Servicemodus versetzen.

.Bevor Sie beginnen
* Das Speichersystem muss über zwei Controller verfügen. Der Controller, den Sie nicht in den Servicemodus versetzen, muss online (im optimalen Zustand) sein.
* Stellen Sie sicher, dass keine Volumes verwendet werden oder dass Sie auf allen Hosts, die diese Volumes verwenden, einen Multipath-Treiber installiert haben.


[NOTE]
====
Das Versetzen eines Controllers in den Servicemodus kann die Leistung erheblich beeinträchtigen. Versetzen Sie einen Controller nur dann in den Servicemodus, wenn Sie vom technischen Support dazu aufgefordert werden.

====
.Schritte
. Wählen Sie *Hardware* aus.
. Wenn die Grafik die Laufwerke anzeigt, klicken Sie auf die Registerkarte *Controllers & Components*.
+
Die Grafik ändert sich, um die Steuergeräte anstelle der Laufwerke anzuzeigen.

. Klicken Sie auf den Controller, den Sie in den Servicemodus versetzen möchten.
+
Das Kontextmenü des Controllers wird angezeigt.

. Wählen Sie *Place in service mode* und bestätigen Sie, dass Sie den Vorgang durchführen möchten.

