---
permalink: sm-hardware/reconstruct-drive-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reconstruct, drive, manually, 
summary: Die Laufwerksrekonstruktion startet normalerweise automatisch nach dem Austausch eines Laufwerks. Wenn die Laufwerksrekonstruktion nicht automatisch startet, können Sie die Rekonstruktion manuell starten. 
---
= Ein Laufwerk manuell im SANtricity System Manager rekonstruieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Laufwerksrekonstruktion startet normalerweise automatisch nach dem Austausch eines Laufwerks. Wenn die Laufwerksrekonstruktion nicht automatisch startet, können Sie die Rekonstruktion manuell starten.

[NOTE]
====
Führen Sie diesen Vorgang nur durch, wenn Sie vom technischen Support oder dem Recovery Guru dazu aufgefordert werden.

====
.Schritte
. Wählen Sie *Hardware* aus.
. Wenn die Grafik die Controller anzeigt, klicken Sie auf die Registerkarte *Drives*.
+
Die Grafik ändert sich, um die Laufwerke anstelle der Controller anzuzeigen.

. Klicken Sie auf das Laufwerk, das Sie manuell rekonstruieren möchten.
+
Das Kontextmenü des Laufwerks wird angezeigt.

. Wählen Sie *Reconstruct* und bestätigen Sie, dass Sie den Vorgang durchführen möchten.

