---
permalink: sm-settings/access-management-with-directory-services.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, directory services, 
summary: 'Für Access Management können Administratoren einen LDAP (Lightweight Directory Access Protocol) Server und einen Verzeichnisdienst wie Microsoft’s Active Directory verwenden.' 
---
= Konfigurieren Sie die Zugriffsverwaltung mit Verzeichnisdiensten im SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für Access Management können Administratoren einen LDAP (Lightweight Directory Access Protocol) Server und einen Verzeichnisdienst wie Microsoft's Active Directory verwenden.



== Konfigurationsworkflow

Wenn im Netzwerk ein LDAP-Server und ein Verzeichnisdienst verwendet werden, funktioniert die Konfiguration wie folgt:

. Ein Administrator meldet sich beim System Manager mit einem Benutzerprofil an, das Security Admin-Berechtigungen enthält.
+
[NOTE]
====
Der `admin` Benutzer hat vollen Zugriff auf alle Funktionen im System.

====
. Der Administrator gibt die Konfigurationseinstellungen für den LDAP-Server ein. Zu den Einstellungen gehören der Domänenname, die URL und die Bind-Kontoinformationen.
. Wenn der LDAP-Server ein sicheres Protokoll (LDAPS) verwendet, lädt der Administrator eine Zertifikatskette einer Certificate Authority (CA) zur Authentifizierung zwischen dem LDAP-Server und dem Storage-Array hoch.
. Nachdem die Serververbindung hergestellt wurde, ordnet der Administrator die Benutzergruppen den Rollen des Storage Arrays zu. Diese Rollen sind vordefiniert und können nicht geändert werden.
. Der Administrator testet die Verbindung zwischen dem LDAP-Server und dem Storage-Array.
. Benutzer melden sich mit ihren zugewiesenen LDAP/Directory Services-Anmeldeinformationen am System an.




== Management

Bei der Verwendung von Verzeichnisdiensten zur Authentifizierung können Administratoren die folgenden Verwaltungsaufgaben durchführen:

* Fügen Sie einen Verzeichnisserver hinzu.
* Verzeichnisserver-Einstellungen bearbeiten.
* LDAP-Benutzer lokalen Benutzerrollen zuordnen.
* Einen Verzeichnisserver entfernen.

