---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Sie können die Benutzerpasswörter für jedes Benutzerprofil in der Zugriffsverwaltung ändern. 
---
= Passwörter im SANtricity System Manager ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Benutzerpasswörter für jedes Benutzerprofil in der Zugriffsverwaltung ändern.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, was Root-Admin-Berechtigungen einschließt.
* Sie müssen das lokale Administratorkennwort kennen.


.Über diese Aufgabe
Beachten Sie diese Richtlinien bei der Wahl eines Passworts:

* Alle neuen lokalen Benutzerpasswörter müssen mindestens der aktuellen Einstellung für ein Mindestpasswort entsprechen (unter Einstellungen anzeigen/bearbeiten).
* Passwörter sind Groß-/Kleinschreibung.
* Nachfolgende Leerzeichen werden beim Festlegen von Passwörtern nicht entfernt. Achten Sie darauf, Leerzeichen beizubehalten, falls sie im Passwort enthalten waren.
* Für erhöhte Sicherheit verwenden Sie mindestens 15 alphanumerische Zeichen und ändern das Passwort häufig.


[NOTE]
====
Eine Passwortänderung im System Manager ändert das Passwort auch in der Befehlszeile (CLI). Darüber hinaus führt eine Passwortänderung zur Beendigung der aktiven Benutzersitzung.

====
.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie die Registerkarte *Local User Roles* aus.
. Wählen Sie einen Benutzer aus der Tabelle.
+
Die Schaltfläche „Passwort ändern“ wird verfügbar.

. Wählen Sie *Change Password*.
+
Das Dialogfeld „Passwort ändern“ wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestlänge festgelegt ist, können Sie das Kontrollkästchen aktivieren, um den ausgewählten Benutzer zur Eingabe eines Passworts für den Zugriff auf das Storage-Array zu verpflichten, und dann können Sie das neue Passwort für den ausgewählten Benutzer eingeben.
. Geben Sie Ihr lokales Administratorpasswort ein, und klicken Sie anschließend auf *Ändern*.


.Ergebnisse
Wenn der Benutzer aktuell angemeldet ist, führt die Passwortänderung dazu, dass die aktive Sitzung des Benutzers beendet wird.
