---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Sie können die Mindestlänge für alle neuen oder aktualisierten Passwörter lokaler Benutzer auf dem Storage-Array festlegen. Sie können lokalen Benutzern auch den Zugriff auf das Storage-Array ohne Passworteingabe ermöglichen. 
---
= Ändern der lokalen Benutzerkennworteinstellungen in SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Mindestlänge für alle neuen oder aktualisierten Passwörter lokaler Benutzer auf dem Storage-Array festlegen. Sie können lokalen Benutzern auch den Zugriff auf das Storage-Array ohne Passworteingabe ermöglichen.

.Bevor Sie beginnen
Sie müssen als lokaler Administrator angemeldet sein, was Root-Admin-Berechtigungen einschließt.

.Über diese Aufgabe
Beachten Sie diese Richtlinien bei der Festlegung der Mindestlänge für lokale Benutzerpasswörter:

* Einstellungsänderungen wirken sich nicht auf bestehende lokale Benutzerpasswörter aus.
* Die erforderliche minimale Längeseinstellung für lokale Benutzerpasswörter muss zwischen 0 und 30 Zeichen liegen.
* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Mindestlängeneinstellung erfüllen oder überschreiten.
* Legen Sie keine Mindestlänge für das Passwort fest, wenn lokale Benutzer auf das Speichersystem zugreifen sollen, ohne ein Passwort einzugeben.


.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie die Registerkarte *Local User Roles* aus.
. Wählen Sie die Schaltfläche *View/Edit Settings* aus.
+
Das Dialogfeld „Lokale Benutzerkennworteinstellungen“ wird geöffnet.

. Führen Sie einen der folgenden Schritte aus:
+
** Um lokalen Benutzern den Zugriff auf das Speicherarray _ohne_ Eingabe eines Passworts zu ermöglichen, deaktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens“.
** Um eine Mindestlänge für alle lokalen Benutzerpasswörter festzulegen, aktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens“ und verwenden Sie dann das Drehfeld, um die erforderliche Mindestlänge für alle lokalen Benutzerpasswörter festzulegen.
+
Alle neuen lokalen Benutzerpasswörter müssen mindestens der aktuellen Einstellung entsprechen.



. Klicken Sie auf *Speichern*.

