---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, alerts, 
summary: 'Um Simple Network Management Protocol (SNMP)-Warnungen zu konfigurieren, müssen Sie mindestens einen Server identifizieren, an den der Ereignismonitor des Storage-Arrays SNMP-Traps senden kann. Die Konfiguration erfordert einen Community-Namen oder Benutzernamen sowie eine IP-Adresse für den Server.' 
---
= Konfigurieren von SNMP-Warnungen im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um Simple Network Management Protocol (SNMP)-Warnungen zu konfigurieren, müssen Sie mindestens einen Server identifizieren, an den der Ereignismonitor des Storage Arrays SNMP-Traps senden kann. Die Konfiguration erfordert einen Community-Namen oder Benutzernamen sowie eine IP-Adresse für den Server.

.Bevor Sie beginnen
* Ein Netzwerkserver muss mit einer SNMP-Dienstanwendung konfiguriert sein. Sie benötigen die Netzwerkadresse dieses Servers (entweder eine IPv4- oder eine IPv6-Adresse), damit der Ereignismonitor Trap-Meldungen an diese Adresse senden kann. Sie können mehr als einen Server verwenden (bis zu 10 Server sind zulässig).
* Die Management Information Base (MIB)-Datei wurde auf den Server mit der SNMP-Dienstanwendung kopiert und kompiliert. Diese MIB-Datei definiert die überwachten und verwalteten Daten.
+
Falls Sie die MIB-Datei nicht besitzen, können Sie sie von der NetApp Support-Website herunterladen:

+
** Gehe zu https://mysupport.netapp.com/site/global/dashboard["NetApp Support"^].
** Klicken Sie auf die Registerkarte *Downloads* und wählen Sie dann *Downloads* aus.
** Klicken Sie auf *E-Series SANtricity OS Controller Software*.
** Wählen Sie *Download Latest Release*.
** Melden Sie sich an.
** Akzeptieren Sie die Warnhinweis- und Lizenzvereinbarung.
** Scrollen Sie nach unten, bis Sie die MIB-Datei für Ihren Controllertyp sehen, und klicken Sie dann auf den Link, um die Datei herunterzuladen.




.Über diese Aufgabe
Diese Aufgabe beschreibt, wie Sie den SNMP-Server für Trap-Ziele identifizieren und dann Ihre Konfiguration testen.

.Schritte
. Menü auswählen: Settings[Alerts].
. Wählen Sie die Registerkarte *SNMP* aus.
+
Bei der erstmaligen Einrichtung zeigt die Registerkarte SNMP „Configure Communities/Users.“ an.

. Wählen Sie *Communities/Users konfigurieren*.
+
Das Dialogfeld „SNMP-Version auswählen“ wird geöffnet.

. Wählen Sie die SNMP-Version für die Warnmeldungen, entweder *SNMPv2c* oder *SNMPv3*.
+
Je nach Ihrer Auswahl wird entweder das Dialogfeld „Communities konfigurieren“ oder das Dialogfeld „SNMPv3-Benutzer konfigurieren“ geöffnet.

. Befolgen Sie die entsprechenden Anweisungen für SNMPv2c (communities) oder SNMPv3 (users):
+
** *SNMPv2c (communities)* -- Geben Sie im Dialogfeld „Configure Communities“ eine oder mehrere Community-Zeichenfolgen für die Netzwerkserver ein. Ein Community-Name ist eine Zeichenfolge, die eine bekannte Gruppe von Management-Stationen identifiziert und wird typischerweise von einem Netzwerkadministrator erstellt. Er besteht ausschließlich aus druckbaren ASCII-Zeichen. Sie können bis zu 256 Communities hinzufügen. Wenn Sie fertig sind, klicken Sie auf *Save*.
** *SNMPv3 (Benutzer)* -- Klicken Sie im Dialogfeld *SNMPv3-Benutzer konfigurieren* auf *Hinzufügen* und geben Sie dann die folgenden Informationen ein:
+
*** *Benutzername* -- Geben Sie einen Namen zur Identifizierung des Benutzers ein, der bis zu 31 Zeichen lang sein kann.
*** *Engine ID* -- Wählen Sie die Engine ID aus, die zur Generierung von Authentifizierungs- und Verschlüsselungsschlüsseln für Nachrichten verwendet wird und innerhalb der administrativen Domäne eindeutig sein muss. In den meisten Fällen sollten Sie *Local* auswählen. Wenn Sie eine nicht standardmäßige Konfiguration haben, wählen Sie *Custom*; ein weiteres Feld erscheint, in dem Sie die maßgebliche Engine ID als hexadezimale Zeichenfolge mit einer geraden Anzahl von Zeichen zwischen 10 und 32 eingeben müssen.
*** *Authentifizierungsdaten* – Wählen Sie ein Authentifizierungsprotokoll, das die Identität der Benutzer sicherstellt. Geben Sie anschließend ein Authentifizierungspasswort ein, das erforderlich ist, wenn das Authentifizierungsprotokoll festgelegt oder geändert wird. Das Passwort muss zwischen 8 und 128 Zeichen lang sein.
*** *Datenschutz-Anmeldeinformationen* -- Wählen Sie ein Datenschutzprotokoll aus, das zum Verschlüsseln der Nachrichteninhalte verwendet wird. Geben Sie anschließend ein Datenschutzpasswort ein, das beim Festlegen oder Ändern des Datenschutzprotokolls erforderlich ist. Das Passwort muss zwischen 8 und 128 Zeichen lang sein. Wenn Sie fertig sind, klicken Sie auf *Hinzufügen* und dann auf *Schließen*.




. Klicken Sie auf der Seite „Warnungen“ mit ausgewähltem SNMP-Tab auf *Trap Destinations hinzufügen*.
+
Das Dialogfeld „Fallenziele hinzufügen“ wird geöffnet.

. Geben Sie ein oder mehrere Trap-Ziele ein, wählen Sie die zugehörigen Community-Namen oder Benutzernamen aus und klicken Sie dann auf *Add*.
+
** *Trap-Ziel* -- Geben Sie eine IPv4- oder IPv6-Adresse des Servers ein, auf dem ein SNMP-Dienst ausgeführt wird.
** *Community-Name oder Benutzername* -- Wählen Sie im Dropdown-Menü den Community-Namen (SNMPv2c) oder den Benutzernamen (SNMPv3) für dieses Trap-Ziel aus. (Wenn Sie nur einen definiert haben, erscheint der Name bereits in diesem Feld.)
** *Fehlermeldung bei Authentifizierungsfehler senden* – Wählen Sie diese Option (das Kontrollkästchen) aus, wenn Sie das Trap-Ziel benachrichtigen möchten, sobald eine SNMP-Anfrage aufgrund eines nicht erkannten Community-Namens oder Benutzernamens abgelehnt wird. Nachdem Sie auf *Hinzufügen* geklickt haben, werden die Trap-Ziele und zugehörigen Namen auf der Registerkarte *SNMP* der Seite *Benachrichtigungen* angezeigt.


. Um sicherzustellen, dass eine Trap gültig ist, wählen Sie ein Trap-Ziel aus der Tabelle aus und klicken Sie dann auf *Trap-Ziel testen*, um eine Test-Trap an die konfigurierte Adresse zu senden.


.Ergebnisse
Der Ereignismonitor sendet SNMP-Traps an den/die Server, wann immer ein alarmrelevantes Ereignis eintritt.
