---
permalink: sm-settings/configure-iser-over-infiniband-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iser, over, infiniband, ports, 
summary: Wenn Ihr Controller einen iSER over InfiniBand-Port umfasst, können Sie die Netzwerkverbindung zum Host konfigurieren. 
---
= Konfigurieren Sie iSER über InfiniBand-Ports im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihr Controller einen iSER over InfiniBand-Port umfasst, können Sie die Netzwerkverbindung zum Host konfigurieren.

.Bevor Sie beginnen
* Ihr Controller muss über einen iSER-over-InfiniBand-Port verfügen; andernfalls sind die iSER-over-InfiniBand-Einstellungen im System Manager nicht verfügbar.
* Sie müssen die IP-Adresse der Hostverbindung kennen.


.Schritte
. Menü auswählen:Settings[System].
. Unter *iSER over InfiniBand settings* wählen Sie *Configure iSER over InfiniBand ports*.
. Klicken Sie auf den Controller mit dem iSER over InfiniBand Port, den Sie konfigurieren möchten. Klicken Sie auf *Weiter*.
. Wählen Sie in der Dropdown-Liste den HIC-Port aus, den Sie konfigurieren möchten, und geben Sie dann die IP-Adresse des Hosts ein.
. Klicken Sie auf *Finish*.
. Setzen Sie den iSER über den InfiniBand-Port zurück, indem Sie auf *Ja* klicken.

