---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: Um die Funktion „Laufwerkssicherheit“ zu nutzen, können Sie einen internen Sicherheitsschlüssel erstellen, der von den Controllern und den sicherheitsfähigen Laufwerken im Storage-Array gemeinsam genutzt wird. Interne Schlüssel werden im persistenten Speicher des Controllers verwaltet. 
---
= Erstellen Sie einen internen Sicherheitsschlüssel im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Funktion „Laufwerkssicherheit“ zu nutzen, können Sie einen internen Sicherheitsschlüssel erstellen, der von den Controllern und den sicherheitsfähigen Laufwerken im Storage-Array gemeinsam genutzt wird. Interne Schlüssel werden im persistenten Speicher des Controllers verwaltet.

.Bevor Sie beginnen
* Im Speicher-Array müssen sichere Laufwerke installiert sein. Diese Laufwerke können Full Disk Encryption (FDE) Laufwerke oder Federal Information Processing Standard (FIPS) Laufwerke sein.
* Die Funktion „Laufwerkssicherheit“ muss aktiviert sein. Andernfalls wird während dieses Vorgangs ein Dialogfeld mit der Meldung „Sicherheitsschlüssel kann nicht erstellt werden“ geöffnet. Wenden Sie sich gegebenenfalls an Ihren Speicheranbieter, um Anweisungen zur Aktivierung der Funktion „Laufwerkssicherheit“ zu erhalten.


[NOTE]
====
Wenn sowohl FDE- als auch FIPS-Laufwerke im Storage-Array installiert sind, verwenden sie alle denselben Sicherheitsschlüssel.

====
.Über diese Aufgabe
In dieser Aufgabe definieren Sie eine Kennung und eine Passphrase, die dem internen Sicherheitsschlüssel zugeordnet werden.

[NOTE]
====
Die Passphrase für Drive Security ist unabhängig vom Administratorpasswort des Storage Arrays.

====
.Schritte
. Menü auswählen:Settings[System].
. Unter *Sicherheitsschlüsselverwaltung* wählen Sie *Internen Schlüssel erstellen* aus.
+
Falls Sie noch keinen Sicherheitsschlüssel generiert haben, wird das Dialogfeld „Sicherheitsschlüssel erstellen“ geöffnet.

. Geben Sie Informationen in die folgenden Felder ein:
+
** *Sicherheitsschlüssel-Kennung definieren* – Sie können entweder den Standardwert (Speicherarray-Name und Zeitstempel, der von der Controller-Firmware generiert wird) übernehmen oder einen eigenen Wert eingeben. Sie können bis zu 189 alphanumerische Zeichen ohne Leerzeichen, Satzzeichen oder Symbole eingeben.
+
[NOTE]
====
Es werden automatisch zusätzliche Zeichen generiert und an beide Enden der von Ihnen eingegebenen Zeichenkette angehängt. Die generierten Zeichen gewährleisten, dass der Bezeichner eindeutig ist.

====
** *Passphrase festlegen/Passphrase wiederholen* – Geben Sie eine Passphrase ein und bestätigen Sie diese. Der Wert kann zwischen 8 und 32 Zeichen lang sein und muss jeweils Folgendes enthalten:
+
*** Ein oder mehrere Großbuchstaben. Beachten Sie, dass die Passphrase Groß-/Kleinschreibung beachtet.
*** Eine Zahl (eine oder mehrere).
*** Ein nicht-alphanumerisches Zeichen, wie !, *, @ (eines oder mehrere).




+
[CAUTION]
====
*Notieren Sie sich Ihre Eingaben für die spätere Verwendung*. Wenn Sie ein gesichertes Laufwerk aus dem Storage-Array entfernen müssen, benötigen Sie die Kennung und die Passphrase, um die Laufwerksdaten zu entsperren.

====
. Klicken Sie auf *Create*.
+
Der Sicherheitsschlüssel wird auf dem Controller an einem nicht zugänglichen Ort gespeichert. Zusammen mit dem eigentlichen Schlüssel gibt es eine verschlüsselte Schlüsseldatei, die von Ihrem Browser heruntergeladen wird.

+
[NOTE]
====
Der Pfad für die heruntergeladene Datei kann vom Standard-Downloadverzeichnis Ihres Browsers abhängen.

====
. Notieren Sie sich Ihre Schlüsselkennung, die Passphrase und den Speicherort der heruntergeladenen Schlüsseldatei und klicken Sie dann auf *Schließen*.


.Ergebnisse
Sie können jetzt sichere Volume-Gruppen oder Pools erstellen, oder Sie können die Sicherheit für bestehende Volume-Gruppen und Pools aktivieren.

[NOTE]
====
Wird die Stromversorgung der Laufwerke unterbrochen und anschließend wiederhergestellt, wechseln alle sicherheitsaktivierten Laufwerke in den Sicherheitssperrzustand. In diesem Zustand sind die Daten unzugänglich, bis der Controller bei der Laufwerksinitialisierung den korrekten Sicherheitsschlüssel anwendet. Wird ein gesperrtes Laufwerk physisch entfernt und in ein anderes System eingebaut, verhindert der Sicherheitssperrzustand den unbefugten Zugriff auf die Daten.

====
.Nachdem Sie fertig sind
Sie sollten den Sicherheitsschlüssel validieren, um sicherzustellen, dass die Schlüsseldatei nicht beschädigt ist.
