---
permalink: sm-settings/edit-alert-email-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, email, addresses, alerts, 
summary: Sie können die E-Mail-Adressen der Empfänger ändern, die E-Mail-Benachrichtigungen erhalten. 
---
= E-Mail-Adressen für Benachrichtigungen im SANtricity System Manager bearbeiten
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die E-Mail-Adressen der Empfänger ändern, die E-Mail-Benachrichtigungen erhalten.

.Bevor Sie beginnen
Die E-Mail-Adresse, die Sie bearbeiten möchten, muss auf der Registerkarte E-Mail der Seite Alerts definiert sein.

.Schritte
. Menü auswählen: Settings[Alerts].
. Wählen Sie die Registerkarte *E-Mail* aus.
. Wählen Sie in der Tabelle *Email Address* die Adresse aus, die Sie ändern möchten, und klicken Sie dann auf das Symbol *Edit* (Stift) ganz rechts.
+
Die Zeile wird zu einem bearbeitbaren Feld.

. Geben Sie eine neue Adresse ein, und klicken Sie dann auf das Symbol *Speichern* (Häkchen).
+
[NOTE]
====
Wenn Sie Änderungen abbrechen möchten, wählen Sie das Symbol *Cancel* (X).

====


.Ergebnisse
Die Registerkarte „E-Mail“ auf der Seite „Benachrichtigungen“ zeigt die aktualisierten E-Mail-Adressen an.
