---
permalink: sm-settings/edit-directory-server-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, directory, server, settings, role, mappings, 
summary: Wenn Sie zuvor einen Verzeichnisserver in der Zugriffsverwaltung konfiguriert haben, können Sie dessen Einstellungen jederzeit ändern. Zu den Einstellungen gehören die Serververbindungsinformationen und die Zuordnung von Gruppen zu Rollen. 
---
= Bearbeiten Sie die Verzeichnisservereinstellungen und Rollenzuordnungen im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zuvor einen Verzeichnisserver in der Zugriffsverwaltung konfiguriert haben, können Sie dessen Einstellungen jederzeit ändern. Zu den Einstellungen gehören die Serververbindungsinformationen und die Zuordnung von Gruppen zu Rollen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Security admin-Berechtigungen verfügt. Andernfalls werden die Access Management-Funktionen nicht angezeigt.
* Ein Verzeichnisserver muss definiert werden.


.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie die Registerkarte *Directory Services* aus.
. Wenn mehr als ein Server definiert ist, wählen Sie den Server, den Sie bearbeiten möchten, aus der Tabelle.
. Wählen Sie *View/Edit Settings* aus.
+
Das Dialogfeld „Verzeichnisservereinstellungen“ wird geöffnet.

. Ändern Sie im Tab „Servereinstellungen“ die gewünschten Einstellungen.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
*Konfigurationseinstellungen*



 a| 
Domäne(n)
 a| 
Die Domänennamen der LDAP-Server. Bei mehreren Domänen geben Sie die Domänen in einer durch Kommas getrennten Liste ein. Der Domänenname wird beim Login (_Benutzername_@_Domäne_) verwendet, um anzugeben, gegen welchen Verzeichnisserver authentifiziert werden soll.



 a| 
Server-URL
 a| 
Die URL für den Zugriff auf den LDAP-Server in der Form von  `ldap[s]://host:port`.



 a| 
Konto binden (optional)
 a| 
Das schreibgeschützte Benutzerkonto für Suchanfragen gegen den LDAP-Server und für die Suche innerhalb der Gruppen.



 a| 
Bind-Passwort (optional)
 a| 
Das Passwort für das Bind-Konto. (Dieses Feld wird angezeigt, wenn ein Bind-Konto eingegeben wird.)



 a| 
Testen Sie die Serververbindung vor dem Speichern
 a| 
Prüft, ob das Speichersystem mit der LDAP-Serverkonfiguration kommunizieren kann. Der Test erfolgt, nachdem Sie unten im Dialogfeld auf *Speichern* klicken. Wenn dieses Kontrollkästchen aktiviert ist und der Test fehlschlägt, wird die Konfiguration nicht geändert. Sie müssen den Fehler beheben oder das Kontrollkästchen deaktivieren, um den Test zu überspringen und die Konfiguration erneut zu bearbeiten.



 a| 
*Berechtigungseinstellungen*



 a| 
Suchbasis-DN
 a| 
Der LDAP-Kontext zur Suche nach Benutzern, typischerweise in der Form  `CN=Users, DC=cpoc, DC=local`.



 a| 
Benutzername-Attribut
 a| 
Das Attribut, das an die Benutzer-ID für die Authentifizierung gebunden ist. Zum Beispiel: `sAMAccountName`.



 a| 
Gruppenattribut(e)
 a| 
Eine Liste der Gruppenattribute des Benutzers, die für die Zuordnung von Gruppen zu Rollen verwendet wird. Zum Beispiel: `memberOf, managedObjects`.

|===
====
. Ändern Sie auf der Registerkarte „Rollenzuordnung“ die gewünschte Zuordnung.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
*Zuordnungen*



 a| 
Gruppen-DN
 a| 
Der Domänenname der zuzuordnenden LDAP-Benutzergruppe. Reguläre Ausdrücke werden unterstützt. Diese Sonderzeichen regulärer Ausdrücke müssen mit einem Backslash (`\`) maskiert werden, wenn sie nicht Teil eines regulären Ausdrucksmusters sind: \.[]{}()<>*+-=!?^$|



 a| 
Rollen
 a| 
Die Rollen des Speichersystems, die dem Gruppen-DN zugeordnet werden sollen. Sie müssen jede Rolle, die Sie für diese Gruppe einschließen möchten, einzeln auswählen. Die Rolle Monitor ist in Kombination mit den anderen Rollen erforderlich, um sich beim SANtricity System Manager anzumelden. Die Rollen des Speichersystems umfassen Folgendes:

** *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf die Speicherobjekte (zum Beispiel Volumes und Disk Pools), jedoch kein Zugriff auf die Sicherheitskonfiguration.
** *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management, Zertifikatsverwaltung, Revisionsprotokollverwaltung und die Möglichkeit, die Legacy-Managementoberfläche (SYMbol) ein- oder auszuschalten.
** *Support admin* -- Zugriff auf alle Hardware-Ressourcen des Storage Arrays, Fehlerdaten, MEL-Ereignisse und Controller-Firmware-Upgrades. Kein Zugriff auf Storage-Objekte oder die Sicherheitskonfiguration.
** *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


|===
====
+
[NOTE]
====
Die Rolle „Monitor“ ist für alle Benutzer, einschließlich des Administrators, erforderlich. System Manager funktioniert für keinen Benutzer ordnungsgemäß, wenn die Rolle „Monitor“ nicht vorhanden ist.

====
. Klicken Sie bei Bedarf auf *Weitere Zuordnung hinzufügen*, um weitere Gruppen-zu-Rollen-Zuordnungen einzugeben.
. Klicken Sie auf *Speichern*.


.Ergebnisse
Nach Abschluss dieser Aufgabe werden alle aktiven Benutzersitzungen beendet. Nur Ihre aktuelle Benutzersitzung bleibt erhalten.
