---
permalink: sm-settings/edit-syslog-server-settings-for-audit-log-records.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, syslog, server, settings, audit, log, records, 
summary: 'Sie können die Einstellungen für den Syslog-Server ändern, der zum Archivieren von Revisionsprotokollen verwendet wird, und auch ein neues Certificate Authority (CA) Zertifikat für den Server hochladen.' 
---
= Bearbeiten Sie die Syslog-Servereinstellungen für Revisionsprotokolleinträge im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für den Syslog-Server ändern, der zum Archivieren von Revisionsprotokollen verwendet wird, und auch ein neues Certificate Authority (CA) Zertifikat für den Server hochladen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Security admin-Berechtigungen verfügt. Andernfalls werden die Access Management-Funktionen nicht angezeigt.
* Die Adresse, das Protokoll und die Portnummer des Syslog-Servers müssen verfügbar sein. Die Serveradresse kann eine vollqualifizierte Domain, eine IPv4-Adresse oder eine IPv6-Adresse sein.
* Wenn Sie ein neues CA-Zertifikat hochladen, muss das Zertifikat auf Ihrem lokalen System verfügbar sein.


.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie auf der Registerkarte „Revisionsprotokoll“ die Option *Syslog-Server konfigurieren*.
+
Konfigurierte Syslog-Server werden auf der Seite angezeigt.

. Um die Serverinformationen zu bearbeiten, wählen Sie das Symbol *Bearbeiten* (Stift) rechts neben dem Servernamen aus, und nehmen Sie dann die gewünschten Änderungen in den folgenden Feldern vor:
+
** *Serveradresse* -- Geben Sie eine vollqualifizierte Domain, eine IPv4-Adresse oder eine IPv6-Adresse ein.
** *Protokoll* -- Wählen Sie ein Protokoll aus der Dropdown-Liste (zum Beispiel TLS, UDP oder TCP).
** *Port* -- Geben Sie die Portnummer für den Syslog-Empfänger ein.


. Wenn Sie das Protokoll auf das sichere TLS-Protokoll (von entweder UDP oder TCP) geändert haben, klicken Sie auf *Vertrauenswürdiges Zertifikat importieren*, um ein CA-Zertifikat hochzuladen.
. Um die neue Verbindung mit dem Storage-Array zu testen, wählen Sie *Test All*.


.Ergebnisse
Nach der Konfiguration werden alle neuen Revisionsprotokolle an den Syslog-Server gesendet. Frühere Protokolle werden nicht übertragen.
