---
permalink: sm-settings/edit-user-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, user, settings, snmpv3, traps, 
summary: Sie können Benutzerdefinitionen für SNMPv3-Traps bearbeiten. 
---
= Benutzereinstellungen für SNMPv3-Traps im SANtricity System Manager bearbeiten
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Benutzerdefinitionen für SNMPv3-Traps bearbeiten.

.Bevor Sie beginnen
Für den SNMPv3 trap muss ein Benutzer angelegt werden.

.Schritte
. Menü auswählen: Settings[Alerts].
. Wählen Sie die Registerkarte *SNMP* aus.
+
Die Trap-Ziele und Benutzernamen werden in der Tabelle angezeigt.

. Um eine Benutzerdefinition zu bearbeiten, wählen Sie den Benutzer in der Tabelle aus und klicken Sie dann auf *Configure Users*.
. Klicken Sie im Dialog auf *Einstellungen anzeigen/bearbeiten*.
. Bearbeiten Sie die folgenden Informationen:
+
** *Benutzername* -- Ändern Sie den Namen, der den Benutzer identifiziert, der bis zu 31 Zeichen lang sein kann.
** *Engine ID* -- Wählen Sie die Engine ID aus, die zur Generierung von Authentifizierungs- und Verschlüsselungsschlüsseln für Nachrichten verwendet wird und innerhalb der administrativen Domäne eindeutig sein muss. In den meisten Fällen sollten Sie *Local* auswählen. Wenn Sie eine nicht standardmäßige Konfiguration haben, wählen Sie *Custom*; ein weiteres Feld erscheint, in dem Sie die maßgebliche Engine ID als hexadezimale Zeichenfolge mit einer geraden Anzahl von Zeichen zwischen 10 und 32 eingeben müssen.
** *Authentifizierungsdaten* – Wählen Sie ein Authentifizierungsprotokoll, das die Identität der Benutzer sicherstellt. Geben Sie anschließend ein Authentifizierungspasswort ein, das erforderlich ist, wenn das Authentifizierungsprotokoll festgelegt oder geändert wird. Das Passwort muss zwischen 8 und 128 Zeichen lang sein.
** *Datenschutz-Zugangsdaten* – Wählen Sie ein Datenschutzprotokoll aus, das zum Verschlüsseln der Nachrichteninhalte verwendet wird. Geben Sie anschließend ein Datenschutzpasswort ein, das erforderlich ist, wenn das Datenschutzprotokoll festgelegt oder geändert wird. Das Passwort muss zwischen 8 und 128 Zeichen lang sein.




.Ergebnisse
Auf der Registerkarte „SNMP“ der Seite „Warnungen“ werden die aktualisierten Einstellungen angezeigt.
