---
permalink: sm-settings/enable-premium-feature.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, premium, feature, 
summary: Eine Premium-Funktion ist eine zusätzliche Option, die einen Schlüssel zur Aktivierung benötigt. 
---
= Aktivieren Sie eine Premium-Funktion im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Premium-Funktion ist eine zusätzliche Option, die einen Schlüssel zur Aktivierung benötigt.

.Bevor Sie beginnen
* Sie haben einen Funktionsschlüssel erhalten. Wenden Sie sich gegebenenfalls an den technischen Support, um einen Schlüssel zu erhalten.
* Sie haben die Schlüsseldatei auf dem Management-Client (dem System mit einem Browser für den Zugriff auf System Manager) geladen.


.Über diese Aufgabe
Diese Aufgabe beschreibt, wie Sie mit System Manager eine Premium-Funktion aktivieren.

[NOTE]
====
Wenn Sie eine Premium-Funktion deaktivieren möchten, müssen Sie den Befehl Disable Storage Array Feature (`disable storageArray) (featurePack | feature=featureAttributeList` in der Befehlszeile (CLI) verwenden.

====
.Schritte
. Menü auswählen:Settings[System].
. Unter *Add-ons* wählen Sie *Enable Premium Feature*.
+
Das Dialogfeld „Premium-Funktion aktivieren“ wird geöffnet.

. Klicken Sie auf *Durchsuchen*, und wählen Sie dann die Schlüsseldatei aus.
+
Der Dateiname wird im Dialogfeld angezeigt.

. Klicken Sie auf *Enable*.

