---
permalink: sm-settings/faq-storage-system-alerts.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur eine schnelle Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen zu Warnmeldungen des Storage-Systems für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur eine schnelle Antwort auf eine Frage suchen.



== Was passiert, wenn Benachrichtigungen deaktiviert sind?

Wenn Sie möchten, dass Administratoren Benachrichtigungen über wichtige Ereignisse erhalten, die im Speichersystem auftreten, müssen Sie eine Benachrichtigungsmethode konfigurieren.

Für Speicher-Arrays, die mit SANtricity System Manager verwaltet werden, konfigurieren Sie Warnmeldungen auf der Seite Alerts. Warnmeldungen können per E-Mail, SNMP-Traps oder Syslog-Nachrichten versendet werden. Zusätzlich können E-Mail-Warnmeldungen über den Initial Setup Wizard konfiguriert werden.



== Wie konfiguriere ich SNMP- oder syslog-Warnungen?

Zusätzlich zu E-Mail-Benachrichtigungen können Sie Benachrichtigungen so konfigurieren, dass sie per Simple Network Management Protocol (SNMP)-Traps oder per Syslog-Meldungen gesendet werden.

Um SNMP- oder Syslog-Warnungen zu konfigurieren, gehen Sie zu menu:Settings[Alerts].



== Warum sind die Zeitstempel zwischen dem Array und den Benachrichtigungen inkonsistent?

Wenn das Speichersystem Warnmeldungen sendet, wird die Zeitzone des Zielservers oder -hosts, der die Warnmeldungen empfängt, nicht berücksichtigt. Stattdessen verwendet das Speichersystem die lokale Zeit (GMT), um den Zeitstempel für den Warnmeldungsdatensatz zu erstellen. Daher können Inkonsistenzen zwischen den Zeitstempeln des Speichersystems und des Servers oder Hosts, der eine Warnmeldung empfängt, auftreten.

Da das Speichersystem beim Senden von Benachrichtigungen keine Zeitzonenkorrektur vornimmt, ist der Zeitstempel der Benachrichtigungen GMT-relativ und weist somit einen Zeitzonenversatz von null auf. Um einen für Ihre lokale Zeitzone passenden Zeitstempel zu berechnen, sollten Sie Ihren Stundenversatz von GMT ermitteln und diesen Wert dann zu den Zeitstempeln addieren oder davon subtrahieren.
