---
permalink: sm-settings/how-access-management-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, authentication, users, roles, access, Management, 
summary: Zugriffsmanagement ist eine Methode zur Einrichtung der Benutzerauthentifizierung im SANtricity System Manager. 
---
= Wie die Zugriffsverwaltung im SANtricity System Manager funktioniert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zugriffsmanagement ist eine Methode zur Einrichtung der Benutzerauthentifizierung im SANtricity System Manager.

Konfiguration und Benutzerauthentifizierung funktionieren wie folgt:

. Ein Administrator meldet sich beim System Manager mit einem Benutzerprofil an, das Security Admin-Berechtigungen enthält.
+
[NOTE]
====
Beim erstmaligen Anmelden wird der Benutzername `admin` automatisch angezeigt und kann nicht geändert werden. Der `admin` Benutzer hat vollen Zugriff auf alle Funktionen im System.

====
. Der Administrator navigiert in der Benutzeroberfläche zur Zugriffsverwaltung. Das Speichersystem ist vorkonfiguriert für die Verwendung lokaler Benutzerrollen, die eine Implementierung der rollenbasierten Zugriffssteuerung (RBAC) darstellen.
. Der Administrator konfiguriert eines oder mehrere der folgenden Authentifizierungsverfahren:
+
** *Lokale Benutzerrollen* -- Die Authentifizierung wird durch rollenbasierte Zugriffssteuerung (RBAC) durchgesetzt, die im Speichersystem implementiert ist. Lokale Benutzerrollen umfassen vordefinierte Benutzerprofile und Rollen mit spezifischen Zugriffsberechtigungen. Administratoren können diese lokalen Benutzerrollen als einziges Authentifizierungsverfahren verwenden oder sie in Kombination mit einem Verzeichnisdienst einsetzen. Es ist keine Konfiguration erforderlich, außer der Festlegung von Passwörtern für Benutzer.
** *Verzeichnisdienste* -- Die Authentifizierung wird über einen LDAP-Server (Lightweight Directory Access Protocol) und einen Verzeichnisdienst wie Microsoft's Active Directory verwaltet. Ein Administrator stellt eine Verbindung zum LDAP-Server her und ordnet dann die LDAP-Benutzer den im Speicher-Array eingebetteten lokalen Benutzerrollen zu.
** *SAML* -- Die Authentifizierung wird über einen Identity Provider (IdP) mithilfe der Security Assertion Markup Language (SAML) 2.0 verwaltet. Ein Administrator stellt die Kommunikation zwischen dem IdP-System und dem Storage Array her und ordnet dann die IdP-Benutzer den im Storage Array eingebetteten lokalen Benutzerrollen zu.


. Der Administrator stellt den Benutzern die Anmeldeinformationen für System Manager zur Verfügung.
. Benutzer melden sich am System an, indem sie ihre Zugangsdaten eingeben.
+
[NOTE]
====
Wenn die Authentifizierung mit SAML und einem SSO (Single Sign-On) verwaltet wird, kann das System den System Manager-Anmeldedialog umgehen.

====
+
Während des Anmeldevorgangs führt das System die folgenden Hintergrundaufgaben aus:

+
** Authentifiziert den Benutzernamen und das Passwort anhand des Benutzerkontos.
** Ermittelt die Berechtigungen des Benutzers anhand der zugewiesenen Rollen.
** Ermöglicht dem Benutzer den Zugriff auf Aufgaben in der Benutzeroberfläche.
** Zeigt den Benutzernamen oben rechts in der Benutzeroberfläche an.






== Im System Manager verfügbare Aufgaben

Der Zugriff auf Aufgaben hängt von den einem Benutzer zugewiesenen Rollen ab, die Folgendes umfassen:

* *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf die Speicherobjekte (zum Beispiel Volumes und Disk Pools), jedoch kein Zugriff auf die Sicherheitskonfiguration.
* *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management, Zertifikatsverwaltung, Revisionsprotokollverwaltung und die Möglichkeit, die Legacy-Managementoberfläche (SYMbol) ein- oder auszuschalten.
* *Support admin* -- Zugriff auf alle Hardware-Ressourcen des Storage Arrays, Fehlerdaten, MEL-Ereignisse und Controller-Firmware-Upgrades. Kein Zugriff auf Storage-Objekte oder die Sicherheitskonfiguration.
* *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


Nicht verfügbare Aufgaben sind entweder ausgegraut oder werden in der Benutzeroberfläche nicht angezeigt. Beispielsweise kann ein Benutzer mit der Rolle Monitor zwar alle Informationen zu Volumes einsehen, aber nicht auf Funktionen zum Ändern dieses Volumes zugreifen. Die Registerkarten für Funktionen wie *Copy Services* und *Add to Workload* sind ausgegraut; nur *View/Edit Settings* ist verfügbar.



== Einschränkungen in Unified Manager und Storage Manager

Wenn SAML für ein Storage Array konfiguriert ist, können Benutzer den Storage für dieses Array weder vom Unified Manager noch von den älteren Storage Manager-Oberflächen aus entdecken oder verwalten.

Wenn lokale Benutzerrollen und Verzeichnisdienste konfiguriert sind, müssen Benutzer Anmeldeinformationen eingeben, bevor sie eine der folgenden Funktionen ausführen:

* Umbenennen des Speicherarrays
* Aktualisierung der Controller-Firmware
* Laden einer Speicherarray-Konfiguration
* Ausführen eines Skripts
* Versuch, eine aktive Operation auszuführen, wenn eine ungenutzte Sitzung abgelaufen ist

