---
permalink: sm-settings/overview-drive-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, system, security, key, management, 
summary: Die Verwaltung von Sicherheitsschlüsseln ist auf der Systemseite verfügbar. 
---
= Erfahren Sie mehr über die Laufwerkssicherheit im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Laufwerkssicherheit und die Schlüsselverwaltung auf der Seite „Sicherheitsschlüsselverwaltung“ konfigurieren.



== Was ist Laufwerkssicherheit?

_Drive Security_ ist eine Funktion, die unbefugten Zugriff auf Daten auf sicherheitsaktivierten Laufwerken verhindert, wenn diese aus dem Storage-Array entfernt werden. Diese Laufwerke können entweder Full Disk Encryption (FDE) Laufwerke oder Federal Information Processing Standard (FIPS) Laufwerke sein. Wenn FDE- oder FIPS-Laufwerke physisch aus dem Array entfernt werden, können sie erst wieder betrieben werden, wenn sie in ein anderes Array eingesetzt werden. Zu diesem Zeitpunkt befinden sich die Laufwerke im Security Locked-Zustand, bis der korrekte Sicherheitsschlüssel bereitgestellt wird. Ein _security key_ ist eine Zeichenfolge, die zwischen diesen Laufwerkstypen und den Controllern in einem Storage-Array geteilt wird.

Mehr erfahren:

* link:how-the-drive-security-feature-works.html["So funktioniert die Funktion „Drive Security“"]
* link:how-security-key-management-works.html["Wie die Verwaltung von Sicherheitsschlüsseln funktioniert"]
* link:drive-security-terminology.html["Terminologie der Laufwerkssicherheit"]




== Wie konfiguriere ich die Schlüsselverwaltung?

Um Drive Security zu implementieren, müssen entweder FDE-Laufwerke oder FIPS-Laufwerke im Array installiert sein. Um die Schlüsselverwaltung für diese Laufwerke zu konfigurieren, gehen Sie zu menu:Settings[System > Security key management], wo Sie entweder einen internen Schlüssel aus dem persistenten Speicher des Controllers oder einen externen Schlüssel von einem Schlüsselverwaltungsserver erstellen können. Abschließend aktivieren Sie Drive Security für Pools und Volumengruppen, indem Sie „secure-capable“ in den Volumeneinstellungen auswählen.

Mehr erfahren:

* link:create-internal-security-key.html["Internen Sicherheitsschlüssel erstellen"]
* link:create-external-security-key.html["Externen Sicherheitsschlüssel erstellen"]
* link:../sm-storage/create-pool-manually.html["Pool manuell erstellen"]
* link:../sm-storage/create-volume-group.html["Volumengruppen erstellen"]




== Wie kann ich Laufwerke entsperren?

Wenn Sie die Schlüsselverwaltung konfiguriert haben und anschließend secure-fähige Laufwerke von einem Storage-Array in ein anderes verschieben, müssen Sie den Security Key dem neuen Storage-Array neu zuweisen, um Zugriff auf die verschlüsselten Daten auf den Laufwerken zu erhalten.

Mehr erfahren:

* link:unlock-drives-using-an-internal-security-key.html["Laufwerke entsperren bei Verwendung der internen Schlüsselverwaltung"]
* link:unlock-drives-using-an-external-security-key.html["Laufwerke entsperren bei Verwendung der externen Schlüsselverwaltung"]




== Verwandte Informationen

Erfahren Sie mehr über Aufgaben im Zusammenhang mit dem Schlüsselmanagement:

* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html["Verwenden Sie CA-signierte Zertifikate zur Authentifizierung mit einem Schlüsselverwaltungsserver"]
* link:back-up-security-key.html["Sicherheitsschlüssel sichern"]

