---
permalink: sm-settings/unlock-drives-using-an-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, drives, internal, key, management, 
summary: Wenn Sie die interne Schlüsselverwaltung konfiguriert haben und anschließend sicherheitsfähige Laufwerke von einem Storage-Array in ein anderes verschieben, müssen Sie den Sicherheitsschlüssel dem neuen Storage-Array neu zuweisen, um Zugriff auf die verschlüsselten Daten auf den Laufwerken zu erhalten. 
---
= Laufwerke entsperren bei Verwendung der internen Schlüsselverwaltung im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die interne Schlüsselverwaltung konfiguriert haben und anschließend sicherheitsfähige Laufwerke von einem Storage-Array in ein anderes verschieben, müssen Sie den Sicherheitsschlüssel dem neuen Storage-Array neu zuweisen, um Zugriff auf die verschlüsselten Daten auf den Laufwerken zu erhalten.

.Bevor Sie beginnen
* Auf dem Quell-Array (dem Array, aus dem Sie die Laufwerke entfernen), haben Sie Volumengruppen exportiert und die Laufwerke entfernt. Auf dem Ziel-Array haben Sie die Laufwerke wieder installiert.
+

NOTE: Die Export-/Importfunktion wird in der System Manager-Benutzeroberfläche nicht unterstützt; Sie müssen die Befehlszeile (CLI) verwenden, um eine Volume-Gruppe in ein anderes Storage-Array zu exportieren/importieren.

+
Detaillierte Anweisungen zur Migration einer Volume-Gruppe finden Sie in der  https://kb.netapp.com/["NetApp Wissensdatenbank"^]. Beachten Sie unbedingt die entsprechenden Anweisungen für neuere Arrays, die vom System Manager verwaltet werden, oder für ältere Systeme.

* Die Funktion „Laufwerkssicherheit“ muss aktiviert sein. Andernfalls wird während dieses Vorgangs ein Dialogfeld mit der Meldung „Sicherheitsschlüssel kann nicht erstellt werden“ geöffnet. Wenden Sie sich gegebenenfalls an Ihren Speicheranbieter, um Anweisungen zur Aktivierung der Funktion „Laufwerkssicherheit“ zu erhalten.
* Sie müssen den Sicherheitsschlüssel kennen, der mit den Laufwerken verknüpft ist, die Sie entsperren möchten.
* Die Sicherheitsschlüsseldatei ist auf dem Verwaltungsclient (dem System mit einem Browser, der für den Zugriff auf den System Manager verwendet wird) verfügbar. Wenn Sie die Laufwerke in ein Storage-Array verschieben, das von einem anderen System verwaltet wird, müssen Sie die Sicherheitsschlüsseldatei auf diesen Verwaltungsclient verschieben.


.Über diese Aufgabe
Bei Verwendung der internen Schlüsselverwaltung wird der Sicherheitsschlüssel lokal auf dem Storage Array gespeichert. Ein Sicherheitsschlüssel ist eine Zeichenfolge, die vom Controller und den Laufwerken für lesen/schreiben gemeinsam genutzt wird. Werden die Laufwerke physisch aus dem Array entfernt und in einem anderen installiert, können sie erst wieder verwendet werden, nachdem der korrekte Sicherheitsschlüssel angegeben wurde.

[NOTE]
====
Sie können entweder einen internen Schlüssel aus dem persistenten Speicher des Controllers oder einen externen Schlüssel von einem Schlüsselverwaltungsserver erstellen. In diesem Thema wird das Entsperren von Daten beschrieben, wenn die _interne_ Schlüsselverwaltung verwendet wird. Wenn Sie die _externe_ Schlüsselverwaltung verwendet haben, siehe link:unlock-drives-using-an-external-security-key.html["Laufwerke entsperren bei Verwendung der externen Schlüsselverwaltung"]. Wenn Sie ein Controller-Upgrade durchführen und alle Controller gegen die neueste Hardware austauschen, müssen Sie andere Schritte befolgen, wie im E-Series und SANtricity Dokumentationszentrum unter link:https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html["Laufwerke entsperren"] beschrieben.

====
Sobald Sie sicherheitsfähige Laufwerke in einem anderen Array neu installieren, erkennt dieses Array die Laufwerke und zeigt den Zustand „Achtung erforderlich“ sowie den Status „Sicherheitsschlüssel erforderlich“ an. Um die Laufwerksdaten zu entsperren, wählen Sie die Sicherheitsschlüsseldatei aus und geben die Passphrase für den Schlüssel ein. (Diese Passphrase ist nicht identisch mit dem Administratorpasswort des Speicherarrays.)

Wenn weitere sicherheitsfähige Laufwerke im neuen Speichersystem installiert sind, verwenden diese möglicherweise einen anderen Sicherheitsschlüssel als den, den Sie importieren. Während des Importvorgangs wird der alte Sicherheitsschlüssel nur verwendet, um die Daten für die Laufwerke, die Sie installieren, zu entsperren. Wenn der Entsperrvorgang erfolgreich ist, werden die neu installierten Laufwerke mit dem Sicherheitsschlüssel des Ziel-Speichersystems neu verschlüsselt.

.Schritte
. Menü auswählen:Settings[System].
. Unter *Security key management* wählen Sie *Unlock Secure Drives*.
+
Das Dialogfeld „Sichere Laufwerke entsperren“ wird geöffnet. Alle Laufwerke, die einen Sicherheitsschlüssel benötigen, werden in der Tabelle angezeigt.

. *Optional:* Bewegen Sie den Mauszeiger über eine Laufwerksnummer, um den Standort des Laufwerks (Shelf-Nummer und Bay-Nummer) anzuzeigen.
. Klicken Sie auf *Durchsuchen*, und wählen Sie dann die Sicherheitsschlüsseldatei aus, die dem Laufwerk entspricht, das Sie entsperren möchten.
+
Die von Ihnen ausgewählte Schlüsseldatei wird im Dialogfeld angezeigt.

. Geben Sie die mit dieser Schlüsseldatei verknüpfte Passphrase ein.
+
Die von Ihnen eingegebenen Zeichen sind maskiert.

. Klicken Sie auf *Entsperren*.
+
Wenn der Entsperrvorgang erfolgreich ist, wird im Dialogfeld angezeigt: „The associated secure drives have been unlocked.“



.Ergebnisse
Wenn alle Laufwerke gesperrt und anschließend entsperrt werden, startet jeder Controller im Storage-Array neu. Sind jedoch bereits einige Laufwerke im Ziel-Storage-Array entsperrt, starten die Controller nicht neu.

.Nachdem Sie fertig sind
Auf dem Ziel-Array (dem Array mit den neu installierten Laufwerken) können Sie jetzt Volumengruppen importieren.


NOTE: Die Export-/Importfunktion wird in der System Manager-Benutzeroberfläche nicht unterstützt; Sie müssen die Befehlszeile (CLI) verwenden, um eine Volume-Gruppe in ein anderes Storage-Array zu exportieren/importieren.

Detaillierte Anweisungen zur Migration einer Volume-Gruppe finden Sie in der  https://kb.netapp.com/["NetApp Wissensdatenbank"^].
