---
permalink: sm-support/upgrade-drive-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, drive, firmware 
summary: Sie können ein Upgrade der Laufwerk-Firmware durchführen, um sicherzustellen, dass Sie über alle aktuellen Funktionen und Fehlerbehebungen verfügen. 
---
= Upgrade der Laufwerk-Firmware im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Firmware Ihrer Laufwerke aktualisieren, um sicherzustellen, dass Sie alle neuesten Funktionen und Fehlerbehebungen erhalten.

.Bevor Sie beginnen
* Sie haben Ihre Daten mittels Disk-to-Disk-Backup, Volume-Kopie (in eine Volume-Gruppe, die von dem geplanten Firmware-Upgrade nicht betroffen ist) oder einem Remote Mirror gesichert.
* Das Speichersystem befindet sich im optimalen Status.
* Alle Laufwerke haben den Status „Optimal“.
* Es werden keine Konfigurationsänderungen auf dem Storage-Array ausgeführt.
* Wenn die Laufwerke nur ein Offline-Upgrade ermöglichen, wird die I/O-Aktivität auf allen mit den Laufwerken verbundenen Volumes gestoppt.


.Schritte
. Menü auswählen: Support[Upgrade Center].
. Laden Sie die neuen Dateien von der Support site auf Ihren Management-Client herunter.
. Klicken Sie unter Upgrade der Laufwerk-Firmware auf *Upgrade starten*.
+
Es erscheint ein Dialogfeld, in dem die aktuell verwendeten Laufwerk-Firmware-Dateien aufgelistet sind.

. Entpacken (entzippen) Sie die Dateien, die Sie von der Support-Website heruntergeladen haben.
. Klicken Sie auf *Durchsuchen*, und wählen Sie die neuen Laufwerks-Firmware-Dateien aus, die Sie von der Support-Website heruntergeladen haben.
+
Firmware-Dateien für Laufwerke haben einen Dateinamen ähnlich wie  `D_HUC101212CSS600_30602291_MS01_2800_0002` mit der Erweiterung  `.dlp`.

+
Sie können bis zu vier Laufwerk-Firmware-Dateien jeweils einzeln auswählen. Wenn mehr als eine Laufwerk-Firmware-Datei mit demselben Laufwerk kompatibel ist, erhalten Sie einen Dateikonflikt-Fehler. Entscheiden Sie, welche Laufwerk-Firmware-Datei Sie für das Upgrade verwenden möchten, und entfernen Sie die andere.

. Klicken Sie auf *Weiter*.
+
Das Dialogfeld *Laufwerke auswählen* wird angezeigt, in dem die Laufwerke aufgelistet sind, die Sie mit den ausgewählten Dateien aktualisieren können.

+
Es werden nur kompatible Laufwerke angezeigt.

+
Die ausgewählte Firmware für das Laufwerk wird im Bereich „Vorgeschlagene Firmware“ angezeigt. Wenn Sie die Firmware ändern müssen, klicken Sie auf *Zurück*, um zum vorherigen Dialog zurückzukehren.

. Wählen Sie den Typ des Upgrades aus, den Sie durchführen möchten:
+
** *Online (Standard)* -- Zeigt die Laufwerke an, die einen Firmware-Download _während das Speichersystem E/A verarbeitet_ unterstützen. Sie müssen die E/A zu den zugehörigen Volumes, die diese Laufwerke verwenden, bei Auswahl dieser Upgrade-Methode nicht stoppen. Diese Laufwerke werden nacheinander aktualisiert, während das Speichersystem E/A auf diesen Laufwerken verarbeitet.
** *Offline (parallel)* -- Zeigt die Laufwerke an, die einen Firmware-Download _nur während alle I/O-Aktivitäten auf allen Volumes, die die Laufwerke verwenden, gestoppt sind_ unterstützen. Sie müssen alle I/O-Aktivitäten auf allen Volumes stoppen, die die Laufwerke verwenden, die Sie aktualisieren, wenn Sie diese Upgrade-Methode auswählen. Laufwerke, die keine Redundanz haben, müssen als Offline-Vorgang verarbeitet werden. Diese Anforderung gilt für jedes Laufwerk, das mit SSD-Cache, einer RAID 0 Volume-Gruppe oder einem Pool oder einer Volume-Gruppe verbunden ist, die beeinträchtigt ist. Das Offline-(Parallel-)Upgrade ist in der Regel schneller als die Online-(Standard-)Methode.


. Wählen Sie in der ersten Spalte der Tabelle das oder die Laufwerke aus, die Sie upgraden möchten.
. Klicken Sie auf *Start*, und bestätigen Sie, dass Sie den Vorgang ausführen möchten.
+
Wenn Sie das Upgrade abbrechen möchten, klicken Sie auf *Stopp*. Alle laufenden Firmware-Downloads werden abgeschlossen. Alle noch nicht gestarteten Firmware-Downloads werden abgebrochen.

+
[CAUTION]
====
Das Anhalten des Upgrade der Laufwerk-Firmware kann zu Datenverlust oder nicht verfügbaren Laufwerken führen.

====
. *Optional:* Um eine Liste der aktualisierten Elemente anzuzeigen, klicken Sie auf *Save Log*.
+
Die Datei wird im Download-Ordner Ihres Browsers mit dem Namen  `drive_upgrade_log-timestamp.txt` gespeichert.

. Wenn während des Upgrade-Vorgangs einer der folgenden Fehler auftritt, ergreifen Sie die entsprechende empfohlene Maßnahme.


.Fehler und empfohlene Maßnahmen
[%collapsible]
====
[cols="40h,~"]
|===
| Wenn Sie auf diesen Firmware-Downloadfehler stoßen... | Dann gehen Sie wie folgt vor... 


 a| 
Fehlerhafte zugewiesene Laufwerke
 a| 
Eine mögliche Fehlerursache ist, dass das Laufwerk nicht über die erforderliche Signatur verfügt. Stellen Sie sicher, dass das betroffene Laufwerk ein autorisiertes Laufwerk ist. Wenden Sie sich für weitere Informationen an den technischen Support.

Beim Austausch eines Laufwerks stellen Sie sicher, dass das Ersatzlaufwerk eine Kapazität hat, die gleich oder größer ist als die des ausgefallenen Laufwerks, das Sie ersetzen.

Sie können das defekte Laufwerk austauschen, während das Speicher-Array E/A empfängt.



 a| 
Speicherarray prüfen
 a| 
* Stellen Sie sicher, dass jedem Controller eine IP-Adresse zugewiesen wurde.
* Stellen Sie sicher, dass alle mit dem Controller verbundenen Kabel nicht beschädigt sind.
* Stellen Sie sicher, dass alle Kabel fest angeschlossen sind.




 a| 
Integrierte Hot-Spare-Laufwerke
 a| 
Dieser Fehler muss behoben werden, bevor Sie die Firmware aktualisieren können. Starten Sie System Manager und verwenden Sie den Recovery Guru, um das Problem zu lösen.



 a| 
Unvollständige Volumengruppen
 a| 
Wenn eine oder mehrere Volumengruppen oder Datenträgerpools unvollständig sind, müssen Sie diesen Fehler beheben, bevor Sie die Firmware aktualisieren können. Starten Sie System Manager und verwenden Sie den Recovery Guru, um das Problem zu lösen.



 a| 
Exklusive Operationen (außer Hintergrundmedien-/Paritätsscan), die derzeit auf beliebigen Volumengruppen ausgeführt werden
 a| 
Falls ein oder mehrere exklusive Vorgänge laufen, müssen diese abgeschlossen sein, bevor die Firmware aktualisiert werden kann. Verwenden Sie System Manager, um den Fortschritt der Vorgänge zu überwachen.



 a| 
Fehlende Volumes
 a| 
Sie müssen das Problem mit dem fehlenden Volume beheben, bevor die Firmware aktualisiert werden kann. Starten Sie System Manager und verwenden Sie den Recovery Guru, um das Problem zu lösen.



 a| 
Einer der Controller befindet sich in einem anderen Zustand als Optimal
 a| 
Einer der Speicher-Array-Controller benötigt Aufmerksamkeit. Dieser Zustand muss behoben werden, bevor die Firmware aktualisiert werden kann. Starten Sie den System Manager und verwenden Sie den Recovery Guru, um das Problem zu beheben.



 a| 
Nicht übereinstimmende Speicherpartitionsinformationen zwischen Controller Object Graphs
 a| 
Bei der Datenvalidierung auf den Controllern ist ein Fehler aufgetreten. Wenden Sie sich an den technischen Support, um dieses Problem zu beheben.



 a| 
SPM Verify Database Controller-Überprüfung schlägt fehl
 a| 
Auf einem Controller ist ein Fehler in der Zuordnungsdatenbank der Speicherpartitionen aufgetreten. Wenden Sie sich an den technischen Support, um dieses Problem zu beheben.



 a| 
Validierung der Konfigurationsdatenbank \(sofern von der Controller-Version des Storage-Arrays unterstützt\)
 a| 
Auf einem Controller ist ein Konfigurationsdatenbankfehler aufgetreten. Wenden Sie sich an den technischen Support, um dieses Problem zu beheben.



 a| 
MEL-bezogene Prüfungen
 a| 
Wenden Sie sich an den technischen Support, um dieses Problem zu lösen.



 a| 
Mehr als 10 DDE-Informations- oder kritische MEL-Ereignisse wurden in den letzten 7 Tagen gemeldet
 a| 
Wenden Sie sich an den technischen Support, um dieses Problem zu lösen.



 a| 
Mehr als 2 Seite 2C kritische MEL-Ereignisse wurden in den letzten 7 Tagen gemeldet
 a| 
Wenden Sie sich an den technischen Support, um dieses Problem zu lösen.



 a| 
In den letzten 7 Tagen wurden mehr als 2 kritische MEL-Ereignisse für einen degradierten Laufwerkskanal gemeldet
 a| 
Wenden Sie sich an den technischen Support, um dieses Problem zu lösen.



 a| 
Mehr als 4 kritische MEL-Einträge in den letzten 7 Tagen
 a| 
Wenden Sie sich an den technischen Support, um dieses Problem zu lösen.

|===
====
.Nachdem Sie fertig sind
Ihr Upgrade der Laufwerk-Firmware ist abgeschlossen. Sie können den normalen Betrieb wieder aufnehmen.
