---
permalink: san-getstarted/access-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access System Manager 
summary: Um auf die Benutzeroberfläche des System Manager zuzugreifen, geben Sie die IP-Adresse des Controllers in einem Browser ein. Ein Einrichtungsassistent hilft Ihnen beim Einstieg in die Systemkonfiguration. 
---
= Zugriff auf SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um auf die Benutzeroberfläche des SANtricity System Manager zuzugreifen, geben Sie die IP-Adresse des Controllers in einem Browser ein. Ein Einrichtungsassistent hilft Ihnen beim Einstieg in die Systemkonfiguration.

.Bevor Sie beginnen
* Installieren und konfigurieren Sie Ihre Hardware, wie in einer der Express-Konfigurationsanleitungen beschrieben:
+
** https://docs.netapp.com/us-en/e-series/config-linux/index.html["Linux Express-Konfiguration"^]
** https://docs.netapp.com/us-en/e-series/config-vmware/index.html["VMware Express-Konfiguration"^]
** https://docs.netapp.com/us-en/e-series/config-windows/index.html["Windows Express-Konfiguration"^]


* Konfigurieren Sie eine Managementstation, die die folgenden Anforderungen erfüllt:
+
** Mit einem Netzwerk verbunden, das 1 Gbit/s oder schneller ist.
** An dasselbe Subnetz wie die Storage-Management-Ports angeschlossen.
** Wird als separate Station verwendet, anstatt als Host (I/O-angebunden), der für das Datenmanagement verwendet wird.
** Einrichtung für Out-of-Band-Management, bei dem eine Speichermanagementstation Befehle über die Ethernet-Verbindungen zum Controller an das Speichersystem sendet.
** Einrichtung mit einem unterstützten Browser. Siehe link:supported-browsers-os.html["Unterstützte Browser und Betriebssysteme"].




.Schritte
. Geben Sie in Ihrem Browser die folgende URL ein: `+https://<IPAddress>+`
+
`IPAddress` ist die Adresse eines der Speicherarray-Controller.

+
Beim ersten Öffnen von System Manager auf einem noch nicht konfigurierten Array erscheint die Aufforderung, das Administratorkennwort festzulegen.

. Geben Sie das System Manager-Passwort für die admin-Rolle in die Felder Administrator-Passwort festlegen und Passwort bestätigen ein, und klicken Sie dann auf *Passwort festlegen*.
+
Der Einrichtungsassistent wird beim ersten Anmelden gestartet.

. Verwenden Sie den Setup-Assistenten, um die folgenden Aufgaben auszuführen:
+
** *Hardware prüfen (Controller und Laufwerke)* – Überprüfen Sie die Anzahl der Controller und Laufwerke im Storage-Array. Weisen Sie dem Array einen Namen zu.
** *Hosts und Betriebssysteme überprüfen* -- Überprüfen Sie die Host- und Betriebssystemtypen, auf die das Storage-Array zugreifen kann.
** *Pools akzeptieren* -- Übernehmen Sie die empfohlene Poolkonfiguration für die Expressinstallation. Ein Pool ist eine logische Gruppe von Laufwerken.
** *Warnungen konfigurieren* -- Ermöglichen Sie dem System Manager, automatische Benachrichtigungen zu erhalten, wenn ein Problem mit dem Storage-Array auftritt.
** *Aktivieren AutoSupport* -- Überwachen Sie automatisch den Zustand Ihres Storage Arrays und lassen Sie Dispatches an den technischen Support senden.




Weitere Informationen zum Setup Wizard finden Sie unter link:../sm-interface/setup-wizard-overview.html["Übersicht des Setup Wizard"].
