---
permalink: um-certificates/access-management-terminology-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, terminology 
summary: Erfahren Sie, wie die Begriffe der Access Management für SANtricity Unified Manager gelten. 
---
= Erfahren Sie mehr über die Terminologie der Zugriffsverwaltung in SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie die Begriffe der Access Management für SANtricity Unified Manager gelten.

[cols="25h,~"]
|===
| Begriff | Beschreibung 


 a| 
Active Directory
 a| 
Active Directory (AD) ist ein Microsoft-Verzeichnisdienst, der LDAP für Windows-Domänennetzwerke verwendet.



 a| 
Bindung
 a| 
Bind-Operationen dienen der Authentifizierung von Clients am Verzeichnisserver. Normalerweise sind für Bind-Operationen Konto- und Passwort-Anmeldedaten erforderlich, aber einige Server erlauben auch anonyme Bind-Operationen.



 a| 
CA
 a| 
Eine Zertifizierungsstelle (CA) ist eine vertrauenswürdige Instanz, die elektronische Dokumente, sogenannte digitale Zertifikate, für die Internetsicherheit ausstellt. Diese Zertifikate identifizieren Website-Betreiber, was sichere Verbindungen zwischen Clients und Servern ermöglicht.



 a| 
Zertifikat
 a| 
Ein Zertifikat dient der Identifizierung des Website-Inhabers aus Sicherheitsgründen, wodurch verhindert wird, dass Angreifer sich als die Website ausgeben. Das Zertifikat enthält Informationen über den Website-Inhaber und die Identität der vertrauenswürdigen Stelle, die diese Informationen zertifiziert (signiert).



 a| 
LDAP
 a| 
Das Lightweight Directory Access Protocol (LDAP) ist ein Anwendungsprotokoll für den Zugriff auf und die Verwaltung verteilter Verzeichnisinformationsdienste. Dieses Protokoll ermöglicht es vielen verschiedenen Anwendungen und Diensten, sich mit dem LDAP-Server zu verbinden, um Benutzer zu validieren.



 a| 
RBAC
 a| 
Die rollenbasierte Zugriffssteuerung (RBAC) ist eine Methode zur Regelung des Zugriffs auf Computer- oder Netzwerkressourcen basierend auf den Rollen einzelner Benutzer. Unified Manager umfasst vordefinierte Rollen.



 a| 
SAML
 a| 
Security Assertion Markup Language (SAML) ist ein XML-basierter Standard für Authentifizierung und Autorisierung zwischen zwei Entitäten. SAML ermöglicht die Multi-Faktor-Authentifizierung, bei der Benutzer zwei oder mehr Elemente zur Bestätigung ihrer Identität angeben müssen (zum Beispiel ein Passwort und einen Fingerabdruck). Die SAML-Funktion des Speicherarrays ist SAML2.0-konform für Identitätsbestätigung, Authentifizierung und Autorisierung.



 a| 
SSO
 a| 
Single Sign-On (SSO) ist ein Authentifizierungsdienst, der es ermöglicht, mit einem Satz von Anmeldeinformationen auf mehrere Anwendungen zuzugreifen.



 a| 
Web Services Proxy
 a| 
Der Web Services Proxy, der den Zugriff über standardmäßige HTTPS-Mechanismen ermöglicht, erlaubt Administratoren die Konfiguration von Verwaltungsdiensten für Storage-Arrays. Der Proxy kann auf Windows- oder Linux-Hosts installiert werden. Die Unified Manager Schnittstelle ist mit dem Web Services Proxy verfügbar.

|===