---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: Sie können die Mindestlänge für alle neuen oder aktualisierten Passwörter lokaler Benutzer festlegen. Sie können auch lokalen Benutzern den Zugriff auf das System ohne Passworteingabe ermöglichen. 
---
= Lokale Benutzernkennworteinstellungen im SANtricity Unified Manager ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Mindestlänge für alle neuen oder aktualisierten Passwörter lokaler Benutzer festlegen. Sie können auch lokalen Benutzern den Zugriff auf das System ohne Passworteingabe ermöglichen.

.Bevor Sie beginnen
Sie müssen als lokaler Administrator angemeldet sein, was Root-Admin-Berechtigungen einschließt.

.Über diese Aufgabe
Beachten Sie diese Richtlinien bei der Festlegung der Mindestlänge für lokale Benutzerpasswörter:

* Einstellungsänderungen wirken sich nicht auf bestehende lokale Benutzerpasswörter aus.
* Die erforderliche minimale Längeseinstellung für lokale Benutzerpasswörter muss zwischen 0 und 30 Zeichen liegen.
* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Mindestlängeneinstellung erfüllen oder überschreiten.
* Legen Sie keine Mindestlänge für das Passwort fest, wenn Sie möchten, dass lokale Benutzer auf das System zugreifen können, ohne ein Passwort einzugeben.


.Schritte
. Wählen Sie *Access Management*.
. Wählen Sie die Registerkarte *Local User Roles* aus.
. Wählen Sie *View/Edit Settings* aus.
+
Das Dialogfeld „Lokale Benutzerkennworteinstellungen“ wird geöffnet.

. Führen Sie einen der folgenden Schritte aus:
+
** Um lokalen Benutzern den Zugriff auf das System _ohne_ Eingabe eines Passworts zu ermöglichen, deaktivieren Sie das Kontrollkästchen „Alle Passwörter lokaler Benutzer müssen mindestens“.
** Um eine Mindestlänge für alle lokalen Benutzerpasswörter festzulegen, aktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens“ und verwenden Sie dann das Drehfeld, um die erforderliche Mindestlänge für alle lokalen Benutzerpasswörter festzulegen.
+
Alle neuen lokalen Benutzerpasswörter müssen mindestens der aktuellen Einstellung entsprechen.



. Klicken Sie auf *Speichern*.

