---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Sie können die Benutzerpasswörter für jeden Benutzer in Access Management ändern. 
---
= Passwörter für lokale Benutzerprofile im SANtricity Unified Manager ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Benutzerpasswörter für jeden Benutzer in Access Management ändern.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, was Root-Admin-Berechtigungen einschließt.
* Sie müssen das lokale Administratorkennwort kennen.


.Über diese Aufgabe
Beachten Sie diese Richtlinien bei der Wahl eines Passworts:

* Alle neuen lokalen Benutzerpasswörter müssen mindestens der aktuellen Einstellung für ein Mindestpasswort entsprechen (unter Einstellungen anzeigen/bearbeiten).
* Passwörter sind Groß-/Kleinschreibung.
* Nachfolgende Leerzeichen werden beim Festlegen von Passwörtern nicht entfernt. Achten Sie darauf, Leerzeichen einzufügen, wenn sie im Passwort enthalten waren.
* Für erhöhte Sicherheit verwenden Sie mindestens 15 alphanumerische Zeichen und ändern das Passwort häufig.


.Schritte
. Wählen Sie *Access Management*.
. Wählen Sie die Registerkarte *Local User Roles* aus.
. Wählen Sie einen Benutzer aus der Tabelle.
+
Die Schaltfläche „Passwort ändern“ wird verfügbar.

. Wählen Sie *Change Password*.
+
Das Dialogfeld „Passwort ändern“ wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestlänge festgelegt ist, können Sie das Kontrollkästchen aktivieren, um vom Benutzer die Eingabe eines Passworts für den Zugriff auf das System zu verlangen.
. Geben Sie das neue Passwort für den ausgewählten Benutzer in die beiden Felder ein.
. Geben Sie Ihr lokales Administratorkennwort ein, um diesen Vorgang zu bestätigen, und klicken Sie dann auf *Ändern*.


.Ergebnisse
Wenn der Benutzer aktuell angemeldet ist, führt die Passwortänderung dazu, dass die aktive Sitzung des Benutzers beendet wird.
