---
permalink: um-certificates/edit-directory-server-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, edit, directory, server, settings, role, mappings 
summary: Wenn Sie zuvor einen Verzeichnisserver in der Zugriffsverwaltung konfiguriert haben, können Sie dessen Einstellungen jederzeit ändern. Zu den Einstellungen gehören die Serververbindungsinformationen und die Zuordnung von Gruppen zu Rollen. 
---
= Bearbeiten Sie die Verzeichnisservereinstellungen und Rollenzuordnungen in SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zuvor einen Verzeichnisserver in der Zugriffsverwaltung konfiguriert haben, können Sie dessen Einstellungen jederzeit ändern. Zu den Einstellungen gehören die Serververbindungsinformationen und die Zuordnung von Gruppen zu Rollen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Security admin-Berechtigungen verfügt. Andernfalls werden die Access Management-Funktionen nicht angezeigt.
* Ein Verzeichnisserver muss definiert werden.


.Schritte
. Wählen Sie *Access Management*.
. Wählen Sie die Registerkarte *Directory Services* aus.
. Wenn mehr als ein Server definiert ist, wählen Sie den Server, den Sie bearbeiten möchten, aus der Tabelle.
. Wählen Sie *View/Edit Settings* aus.
+
Das Dialogfeld „Verzeichnisservereinstellungen“ wird geöffnet.

. Ändern Sie auf der Registerkarte *Server Settings* die gewünschten Einstellungen.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
*Konfigurationseinstellungen*



 a| 
Domäne(n)
 a| 
Die Domänennamen der LDAP-Server. Bei mehreren Domänen geben Sie die Domänen als durch Kommas getrennte Liste ein. Der Domänenname wird beim Login (_Benutzername_@_Domäne_) verwendet, um anzugeben, gegen welchen Verzeichnisserver authentifiziert werden soll.



 a| 
Server-URL
 a| 
Die URL für den Zugriff auf den LDAP-Server in der Form von  `ldap[s]://host:port`.



 a| 
Konto binden (optional)
 a| 
Das schreibgeschützte Benutzerkonto für Suchanfragen gegen den LDAP-Server und für die Suche innerhalb der Gruppen.



 a| 
Bind-Passwort (optional)
 a| 
Das Passwort für das Bind-Konto. (Dieses Feld wird angezeigt, wenn ein Bind-Konto eingegeben wird.)



 a| 
Testen Sie die Serververbindung vor dem Speichern
 a| 
Prüft, ob das System mit der LDAP-Serverkonfiguration kommunizieren kann. Der Test wird nach dem Klicken auf *Save* durchgeführt. Wenn dieses Kontrollkästchen aktiviert ist und der Test fehlschlägt, wird die Konfiguration nicht geändert. Sie müssen den Fehler beheben oder das Kontrollkästchen deaktivieren, um den Test zu überspringen und die Konfiguration erneut zu bearbeiten.



 a| 
*Berechtigungseinstellungen*



 a| 
Suchbasis-DN
 a| 
Der LDAP-Kontext zur Suche nach Benutzern, typischerweise in der Form  `CN=Users, DC=cpoc, DC=local`.



 a| 
Benutzername-Attribut
 a| 
Das Attribut, das an die Benutzer-ID für die Authentifizierung gebunden ist. Zum Beispiel:
`sAMAccountName`.



 a| 
Gruppenattribut(e)
 a| 
Eine Liste der Gruppenattribute des Benutzers, die für die Zuordnung von Gruppen zu Rollen verwendet wird. Zum Beispiel:
`memberOf, managedObjects`.

|===
====
. Im Tab *Rollenzuordnung* ändern Sie die gewünschte Zuordnung.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
*Zuordnungen*



 a| 
Gruppen-DN
 a| 
Der Domänenname der zuzuordnenden LDAP-Benutzergruppe. Reguläre Ausdrücke werden unterstützt. Diese speziellen regulären Ausdruckszeichen müssen mit einem Backslash (\) maskiert werden, wenn sie nicht Teil eines regulären Ausdrucksmusters sind:

\.[]{}()<>*+-=!?^$|



 a| 
Rollen
 a| 
Die Rollen, die dem Gruppen-DN zugeordnet werden sollen. Sie müssen jede Rolle, die Sie für diese Gruppe einschließen möchten, einzeln auswählen. Die Rolle Monitor ist in Kombination mit den anderen Rollen erforderlich, um sich bei SANtricity Unified Manager anzumelden. Die Rollen umfassen Folgendes:

** *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf Speicherobjekte in den Arrays, jedoch kein Zugriff auf die Sicherheitskonfiguration.
** *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management und Certificate Management.
** *Support-Administrator* -- Zugriff auf alle Hardware-Ressourcen der Speichersysteme, Fehlerdaten und MEL-Ereignisse. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
** *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


|===
====
+

NOTE: Die Rolle Monitor ist für alle Benutzer erforderlich, einschließlich des Administrators.

. Klicken Sie bei Bedarf auf *Weitere Zuordnung hinzufügen*, um weitere Gruppen-zu-Rollen-Zuordnungen einzugeben.
. Klicken Sie auf *Speichern*.


.Ergebnisse
Nach Abschluss dieser Aufgabe werden alle aktiven Benutzersitzungen beendet. Nur Ihre aktuelle Benutzersitzung bleibt erhalten.
