---
permalink: um-certificates/export-saml-service-provider-files.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, export, saml, Service Provider, files, 
summary: 'Bei Bedarf können Sie die Service Provider-Metadaten für das Storage Array exportieren und die Datei anschließend wieder in das Identity Provider (IdP) System importieren.' 
---
= SAML-Dienstanbieterdateien im SANtricity Unified Manager exportieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Bedarf können Sie die Service Provider-Metadaten für das Storage Array exportieren und die Datei anschließend wieder in das Identity Provider (IdP) System importieren.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Security admin-Berechtigungen verfügt. Andernfalls werden die Access Management-Funktionen nicht angezeigt.
* SAML ist konfiguriert und aktiviert.


.Über diese Aufgabe
In dieser Aufgabe exportieren Sie Metadaten vom Controller. Der IdP benötigt diese Metadaten, um eine Vertrauensbeziehung mit dem Controller herzustellen und um Authentifizierungsanfragen zu verarbeiten. Die Datei enthält Informationen wie den Domänennamen oder die IP-Adresse des Controllers, die der IdP zum Senden von Anfragen verwenden kann.

.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie die Registerkarte *SAML* aus.
. Wählen Sie *Export*.
+
Das Dialogfeld „Export Service Provider Files“ wird geöffnet.

. Klicken Sie auf *Export*, um die Metadatendatei auf Ihrem lokalen System zu speichern.
+
[NOTE]
====
Das Feld „Domänenname“ ist schreibgeschützt.

====
+
Notieren Sie sich, wo die Datei gespeichert ist.

. Suchen Sie auf dem lokalen System die im XML-Format vorliegende, exportierte Service Provider-Metadatendatei.
. Importieren Sie vom IdP-Server die Metadatendatei des Service Providers. Sie können die Datei entweder direkt importieren oder Sie können die Controller-Informationen manuell eingeben.
. Klicken Sie auf *Schließen*.

