---
permalink: um-certificates/faq-user-access-mgmt-um.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur eine schnelle Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen zur Benutzerzugriffsverwaltung für SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur eine schnelle Antwort auf eine Frage suchen.



== Warum kann ich mich nicht anmelden?

Falls beim Anmeldeversuch eine Fehlermeldung erscheint, überprüfen Sie diese möglichen Ursachen.

Anmeldefehler können aus einem dieser Gründe auftreten:

* Sie haben einen falschen Benutzernamen oder ein falsches Passwort eingegeben.
* Sie verfügen über unzureichende Berechtigungen.
* Sie haben mehrfach erfolglos versucht, sich anzumelden, wodurch der Sperrmodus ausgelöst wurde. Warten Sie 10 Minuten, um sich erneut anzumelden.
* SAML-Authentifizierung ist aktiviert. Aktualisieren Sie Ihren Browser, um sich anzumelden.




== Was muss ich wissen, bevor ich einen Verzeichnisserver hinzufüge?

Bevor Sie einen Verzeichnisserver in Access Management hinzufügen, müssen Sie bestimmte Voraussetzungen erfüllen.

* Benutzergruppen müssen in Ihrem Verzeichnisdienst definiert werden.
* Die Anmeldeinformationen für den LDAP-Server müssen verfügbar sein, einschließlich des Domainnamens, der Server-URL und optional des Benutzernamens und des Passworts des Bind-Kontos.
* Für LDAPS-Server, die ein sicheres Protokoll verwenden, muss die Zertifikatskette des LDAP-Servers auf Ihrem lokalen Rechner installiert sein.




== Was muss ich über die Zuordnung zu Speicherarray-Rollen wissen?

Bevor Sie Gruppen Rollen zuordnen, überprüfen Sie die Richtlinien.

Die RBAC (rollenbasierte Zugriffssteuerung)-Funktionen umfassen die folgenden Rollen:

* *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf Speicherobjekte in den Arrays, jedoch kein Zugriff auf die Sicherheitskonfiguration.
* *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management und Certificate Management.
* *Support-Administrator* -- Zugriff auf alle Hardware-Ressourcen der Speichersysteme, Fehlerdaten und MEL-Ereignisse. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
* *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


[NOTE]
====
Die Rolle Monitor ist für alle Benutzer erforderlich, einschließlich des Administrators.

====
Wenn Sie einen LDAP (Lightweight Directory Access Protocol)-Server und Verzeichnisdienste verwenden, stellen Sie sicher, dass:

* Ein Administrator hat Benutzergruppen im Verzeichnisdienst definiert.
* Sie kennen die Gruppendomänennamen der LDAP-Benutzergruppen.




=== SAML

Wenn Sie die im Speichersystem integrierten Security Assertion Markup Language (SAML)-Funktionen nutzen, stellen Sie sicher, dass:

* Ein Administrator eines Identity Provider (IdP) hat Benutzerattribute und Gruppenzugehörigkeit im IdP-System konfiguriert.
* Sie kennen die Gruppenzugehörigkeitsnamen.
* Sie kennen den Attributwert der zuzuordnenden Gruppe. Reguläre Ausdrücke werden unterstützt. Diese speziellen Zeichen regulärer Ausdrücke müssen mit einem Backslash (`\`) maskiert werden, wenn sie nicht Teil eines regulären Ausdrucksmusters sind:
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* Die Rolle „Monitor“ ist für alle Benutzer, einschließlich des Administrators, erforderlich. Unified Manager funktioniert für keinen Benutzer ordnungsgemäß, wenn die Rolle „Monitor“ nicht vorhanden ist.




== Was muss ich wissen, bevor ich SAML konfiguriere und aktiviere?

Bevor Sie die Security Assertion Markup Language (SAML)-Funktionen für die Authentifizierung konfigurieren und aktivieren, stellen Sie sicher, dass Sie die folgenden Anforderungen erfüllen und die SAML-Beschränkungen verstehen.



=== Anforderungen

Bevor Sie beginnen, stellen Sie sicher, dass:

* In Ihrem Netzwerk ist ein Identitätsanbieter (IdP) konfiguriert. Ein IdP ist ein externes System, das Anmeldeinformationen von einem Benutzer anfordert und bestimmt, ob der Benutzer erfolgreich authentifiziert wurde. Ihr Sicherheitsteam ist für die Wartung des IdP verantwortlich.
* Ein IdP-Administrator hat Benutzerattribute und Gruppen im IdP-System konfiguriert.
* Ein IdP-Administrator hat sichergestellt, dass der IdP die Möglichkeit unterstützt, bei der Authentifizierung eine Name ID zurückzugeben.
* Ein Administrator hat sichergestellt, dass die Uhr des IdP-Servers und des Controllers synchronisiert ist (entweder über einen NTP-Server oder durch Anpassen der Controller-Uhreinstellungen).
* Eine IdP-Metadatendatei wird vom IdP-System heruntergeladen und ist auf dem lokalen System verfügbar, das für den Zugriff auf Unified Manager verwendet wird.
* Sie kennen die IP-Adresse oder den Domänennamen des Controllers im Storage-Array.




=== Einschränkungen

Zusätzlich zu den oben genannten Anforderungen stellen Sie bitte sicher, dass Sie die folgenden Einschränkungen verstehen:

* Sobald SAML aktiviert ist, können Sie es _nicht_ über die Benutzeroberfläche deaktivieren, noch können Sie die IdP-Einstellungen bearbeiten. Wenn Sie die SAML-Konfiguration deaktivieren oder bearbeiten müssen, wenden Sie sich an den Technical Support, um Unterstützung zu erhalten. Wir empfehlen, dass Sie die SSO-Anmeldungen testen, bevor Sie SAML im letzten Konfigurationsschritt aktivieren. (Das System führt ebenfalls einen SSO-Anmeldetest durch, bevor SAML aktiviert wird.)
* Wenn Sie SAML in Zukunft deaktivieren, stellt das System automatisch die vorherige Konfiguration (Local User Roles und/oder Directory Services) wieder her.
* Wenn die Verzeichnisdienste aktuell für die Benutzerauthentifizierung konfiguriert sind, überschreibt SAML diese Konfiguration.
* Wenn SAML konfiguriert ist, können die folgenden Clients nicht auf Speicherarray-Ressourcen zugreifen:
+
** Enterprise Management Window (EMW)
** Befehlszeilenschnittstelle (CLI)
** Software Developer Kits (SDK)-Clients
** In-Band-Clients
** HTTP Basic Authentication REST-API-Clients
** Anmeldung mit dem Standard-REST-API-Endpunkt






== Was sind die lokalen Nutzer?

Lokale Benutzer sind im System vordefiniert und verfügen über spezifische Berechtigungen.

Zu den lokalen Nutzern gehören:

* *admin* -- Superadministrator mit Zugriff auf alle Funktionen im System. Dieser Benutzer umfasst alle Rollen. Das Passwort muss beim ersten Anmelden festgelegt werden.
* *storage* -- Der Administrator, der für die gesamte Speicherbereitstellung zuständig ist. Dieser Benutzer umfasst die folgenden Rollen: Storage Admin, Support Admin und Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wurde.
* *Sicherheit* -- Der Benutzer, der für die Sicherheitskonfiguration, einschließlich Zugriffsverwaltung und Zertifikatsverwaltung, zuständig ist. Dieser Benutzer umfasst die folgenden Rollen: Security Admin und Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wurde.
* *support* -- Der Benutzer, der für Hardware-Ressourcen, Fehlerdaten und Firmware-Upgrades verantwortlich ist. Dieser Benutzer umfasst die folgenden Rollen: Support Admin und Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wurde.
* *monitor* -- Ein Benutzer mit Lesezugriff auf das System. Dieser Benutzer verfügt ausschließlich über die Rolle Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wird.
* *rw* (lesen/schreiben) -- Dieser Benutzer umfasst die folgenden Rollen: Storage Admin, Support Admin und Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wird.
* *ro* (read only) -- Dieser Benutzer verfügt ausschließlich über die Rolle Monitor. Dieses Konto ist deaktiviert, bis ein Passwort festgelegt wird.

