---
permalink: um-certificates/how-access-management-works-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, authentication, users, roles, access management 
summary: Verwenden Sie Access Management, um die Benutzerauthentifizierung in SANtricity Unified Manager einzurichten. 
---
= Wie die Zugriffsverwaltung in SANtricity Unified Manager funktioniert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie Access Management, um die Benutzerauthentifizierung in SANtricity Unified Manager einzurichten.



== Konfigurationsworkflow

Die Konfiguration der Access Management funktioniert wie folgt:

. Ein Administrator meldet sich mit einem Benutzerprofil, das Security admin-Berechtigungen enthält, bei Unified Manager an.
+
[NOTE]
====
Beim erstmaligen Anmelden wird der Benutzername `admin` automatisch angezeigt und kann nicht geändert werden. Der `admin` Benutzer hat vollen Zugriff auf alle Funktionen im System. Das Passwort muss beim erstmaligen Anmelden festgelegt werden.

====
. Der Administrator navigiert in der Benutzeroberfläche zur Zugriffsverwaltung, die vorkonfigurierte lokale Benutzerrollen enthält. Diese Rollen sind eine Implementierung von RBAC (rollenbasierte Zugriffssteuerung)-Funktionen.
. Der Administrator konfiguriert eines oder mehrere der folgenden Authentifizierungsverfahren:
+
** *Lokale Benutzerrollen* – Die Authentifizierung wird durch rollenbasierte Zugriffssteuerung (RBAC) verwaltet. Lokale Benutzerrollen umfassen vordefinierte Benutzer und Rollen mit spezifischen Zugriffsberechtigungen. Administratoren können diese lokalen Benutzerrollen als einziges Authentifizierungsverfahren verwenden oder sie in Kombination mit einem Verzeichnisdienst einsetzen. Es ist keine Konfiguration erforderlich, außer der Festlegung von Kennwörtern für Benutzer.
** *Verzeichnisdienste* -- Die Authentifizierung erfolgt über einen LDAP-Server (Lightweight Directory Access Protocol) und einen Verzeichnisdienst wie beispielsweise Microsoft's Active Directory. Ein Administrator stellt eine Verbindung zum LDAP-Server her und ordnet anschließend die LDAP-Benutzer den lokalen Benutzerrollen zu.
** *SAML* -- Die Authentifizierung wird über einen Identity Provider (IdP) mithilfe der Security Assertion Markup Language (SAML) 2.0 verwaltet. Ein Administrator stellt die Kommunikation zwischen dem IdP-System und dem Storage Array her und ordnet dann die IdP-Benutzer den im Storage Array eingebetteten lokalen Benutzerrollen zu.


. Der Administrator stellt den Benutzern Anmeldeinformationen für Unified Manager zur Verfügung.
. Benutzer melden sich im System an, indem sie ihre Zugangsdaten eingeben. Während der Anmeldung führt das System die folgenden Hintergrundaufgaben aus:
+
** Authentifiziert den Benutzernamen und das Passwort anhand des Benutzerkontos.
** Ermittelt die Berechtigungen des Benutzers anhand der zugewiesenen Rollen.
** Ermöglicht dem Benutzer den Zugriff auf Funktionen in der Benutzeroberfläche.
** Zeigt den Benutzernamen im oberen Banner an.






== Im Unified Manager verfügbare Funktionen

Der Zugriff auf Funktionen hängt von den einem Benutzer zugewiesenen Rollen ab, die Folgendes umfassen:

* *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf Speicherobjekte in den Arrays, jedoch kein Zugriff auf die Sicherheitskonfiguration.
* *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management und Certificate Management.
* *Support-Administrator* -- Zugriff auf alle Hardware-Ressourcen der Speichersysteme, Fehlerdaten und MEL-Ereignisse. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
* *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


Eine nicht verfügbare Funktion ist entweder ausgegraut oder wird in der Benutzeroberfläche nicht angezeigt.
