---
permalink: um-certificates/import-array-certificates-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, certificates, arrays 
summary: 'Bei Bedarf können Sie Zertifikate für die Storage-Arrays importieren, damit diese sich beim System, auf dem SANtricity Unified Manager ausgeführt wird, authentifizieren können. Zertifikate können von einer Zertifizierungsstelle (CA) signiert oder selbstsigniert sein.' 
---
= Zertifikate für Arrays im SANtricity Unified Manager importieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei Bedarf können Sie Zertifikate für die Storage-Arrays importieren, damit diese sich beim System, auf dem SANtricity Unified Manager ausgeführt wird, authentifizieren können. Zertifikate können von einer Zertifizierungsstelle (CA) signiert oder selbstsigniert sein.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Security admin-Berechtigungen verfügt. Andernfalls werden die Zertifikatsfunktionen nicht angezeigt.
* Wenn Sie vertrauenswürdige Zertifikate importieren, müssen die Zertifikate für die Speicherarray-Controller mit System Manager importiert werden.


.Schritte
. Wählen Sie *Certificate Management*.
. Wählen Sie die Registerkarte *Trusted* aus.
+
Auf dieser Seite werden alle für die Speicherarrays gemeldeten Zertifikate angezeigt.

. Wählen Sie entweder menu:Import[Certificates], um ein CA-Zertifikat zu importieren, oder menu:Import[Self-signed storage array certificates], um ein selbstsigniertes Zertifikat zu importieren.
+
Um die Ansicht einzuschränken, können Sie das Filterfeld *Zertifikate anzeigen, die...* verwenden oder die Zertifikatszeilen sortieren, indem Sie auf eine der Spaltenköpfe klicken.

. Wählen Sie im Dialogfeld das Zertifikat aus und klicken Sie dann auf *Import*.
+
Das Zertifikat wird hochgeladen und validiert.


