---
permalink: um-certificates/permissions-for-mapped-roles-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, permissions, mapped, roles 
summary: 'Die Funktionen der rollenbasierten Zugriffssteuerung (RBAC) umfassen vordefinierte Benutzer mit einer oder mehreren ihnen zugeordneten Rollen. Jede Rolle beinhaltet Berechtigungen für den Zugriff auf Aufgaben im SANtricity Unified Manager.' 
---
= Berechtigungen für zugeordnete Rollen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Funktionen der rollenbasierten Zugriffssteuerung (RBAC) umfassen vordefinierte Benutzer mit einer oder mehreren ihnen zugeordneten Rollen. Jede Rolle beinhaltet Berechtigungen für den Zugriff auf Aufgaben im SANtricity Unified Manager.

Die Rollen gewähren Benutzern Zugriff auf Aufgaben, wie folgt:

* *Speicheradministrator* -- Voller lesen/schreiben-Zugriff auf Speicherobjekte in den Arrays, jedoch kein Zugriff auf die Sicherheitskonfiguration.
* *Sicherheitsadministrator* -- Zugriff auf die Sicherheitskonfiguration in Access Management und Certificate Management.
* *Support-Administrator* -- Zugriff auf alle Hardware-Ressourcen der Speichersysteme, Fehlerdaten und MEL-Ereignisse. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
* *Monitor* -- Nur Lesezugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


Wenn ein Benutzer keine Berechtigungen für eine bestimmte Funktion hat, ist diese Funktion entweder nicht auswählbar oder wird in der Benutzeroberfläche nicht angezeigt.
