---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unberechtigtem Zugriff zu schützen. 
---
= Erfahren Sie mehr über den Administratorpasswortschutz im SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unberechtigtem Zugriff zu schützen.



== Administratorpasswort und Benutzerprofile

Beim ersten Start von Unified Manager werden Sie aufgefordert, ein Administratorpasswort festzulegen. Jeder Benutzer, der das Administratorpasswort hat, kann Konfigurationsänderungen an den Storage Arrays vornehmen.

Zusätzlich zum Administratorkennwort enthält die Unified Manager-Oberfläche vorkonfigurierte Benutzerprofile mit einer oder mehreren zugeordneten Rollen. Weitere Informationen finden Sie unter link:../um-certificates/how-access-management-works-unified.html["Wie die Zugriffsverwaltung funktioniert"].

Benutzer und Zuordnungen können nicht geändert werden. Nur Passwörter können geändert werden. Informationen zum Ändern von Passwörtern finden Sie hier:

* link:change-admin-password-unified.html["Ändern Sie das Administratorpasswort"]
* link:../um-certificates/change-passwords-unified.html["Passwörter für lokale Benutzerprofile ändern"]




== Sitzungs-Timeouts

Die Software fordert Sie während einer Verwaltungssitzung nur einmal zur Passworteingabe auf. Eine Sitzung läuft standardmäßig nach 30 Minuten Inaktivität ab, zu diesem Zeitpunkt müssen Sie das Passwort erneut eingeben. Wenn ein anderer Benutzer während Ihrer Sitzung von einem anderen Verwaltungsclient auf die Software zugreift und das Passwort ändert, werden Sie beim nächsten Versuch einer Konfigurations- oder Ansichtsvorgang zur Passworteingabe aufgefordert.

Aus Sicherheitsgründen können Sie ein Passwort nur fünfmal eingeben, bevor die Software in einen „Lockout“-Zustand wechselt. In diesem Zustand lehnt die Software nachfolgende Passwortversuche ab. Sie müssen 10 Minuten warten, um in den „normalen“ Zustand zurückzukehren, bevor Sie erneut versuchen, ein Passwort einzugeben.

Sie können Sitzungs-Zeitüberschreitungen anpassen oder Sitzungs-Zeitüberschreitungen vollständig deaktivieren. Weitere Informationen finden Sie unter link:manage-session-timeouts-unified.html["Sitzungs-Zeitüberschreitungen verwalten"].
