---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: Sie können das Administratorpasswort ändern, das für den Zugriff auf SANtricity Unified Manager verwendet wird. 
---
= Ändern Sie das Administratorkennwort im SANtricity Unified Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Administratorpasswort ändern, das für den Zugriff auf SANtricity Unified Manager verwendet wird.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, was Root-Admin-Berechtigungen einschließt.
* Sie müssen das aktuelle Administratorpasswort kennen.


.Über diese Aufgabe
Beachten Sie diese Richtlinien bei der Wahl eines Passworts:

* Passwörter sind Groß-/Kleinschreibung.
* Nachfolgende Leerzeichen werden beim Festlegen von Passwörtern nicht entfernt. Achten Sie darauf, Leerzeichen einzufügen, wenn sie im Passwort enthalten waren.
* Für erhöhte Sicherheit verwenden Sie mindestens 15 alphanumerische Zeichen und ändern das Passwort häufig.


.Schritte
. Menü auswählen: Einstellungen[Access Management].
. Wählen Sie die Registerkarte *Local User Roles* aus.
. Wählen Sie den *admin*-Benutzer aus der Tabelle aus.
+
Die Schaltfläche „Passwort ändern“ wird verfügbar.

. Wählen Sie *Change Password*.
+
Das Dialogfeld „Passwort ändern“ wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestlänge festgelegt ist, aktivieren Sie das Kontrollkästchen, um den Benutzer zur Eingabe eines Passworts zu verpflichten, um auf das System zuzugreifen.
. Geben Sie das neue Passwort in die beiden Felder ein.
. Geben Sie Ihr lokales Administratorkennwort ein, um diesen Vorgang zu bestätigen, und klicken Sie dann auf *Ändern*.

