---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: Sie können die Passwörter aktualisieren, die zum Anzeigen und Zugreifen auf Speicherarrays im SANtricity Unified Manager verwendet werden. 
---
= Passwörter für Speicherarrays im SANtricity Unified Manager ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Passwörter aktualisieren, die zum Anzeigen und Zugreifen auf Speicherarrays im SANtricity Unified Manager verwendet werden.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das über Storage-Administratorrechte verfügt.
* Sie müssen das aktuelle Passwort für das Speichersystem kennen, das im System Manager festgelegt ist.


.Über diese Aufgabe
In dieser Aufgabe geben Sie das aktuelle Passwort für ein Storage-Array ein, damit Sie im Unified Manager darauf zugreifen können. Dies kann erforderlich sein, wenn das Array-Passwort im System Manager geändert wurde und nun auch im Unified Manager geändert werden muss.

.Schritte
. Wählen Sie auf der Seite Manage ein oder mehrere Speicherarrays aus.
. Menü auswählen: Uncommon Tasks [Provide Storage Array Passwords].
. Geben Sie das Passwort oder die Passwörter für jedes Speicherarray ein und klicken Sie dann auf *Speichern*.

